### ISSUE TITLE
FTL Update throwing "404 Not Found"

### ISSUE THREAD

**Issue by GatoPharaoh** [arevindh/pihole-speedtest#1]
Core is updated but whenever I try to update my FTL it stops with a 404
Terminal output is a follows:

```
 [i] FTL out of date

[i] FTL Checks...
[i] Downloading and Installing FTL...curl: (22) The requested URL returned error: 404 Not Found
[✗] Downloading and Installing FTL
Error: URL not found
```
Tried all the instrucions - changed resolv.conf to 8.8.8.8 - nothing works, it won't update.
Pihole Version and Web Interface are at 4.0
FTL is stuck at 3.0

**Comment by arevindh** [comment]
Try `pihole checkout master `

**Comment by GatoPharaoh** [comment]
Uninstalled the speedtest-mod and updated.
Now it's working again
