### ISSUE TITLE
Fehler Installation sqlite

### ISSUE THREAD

**Issue by xnetworker** [arevindh/pihole-speedtest#100]
Ich erhalte beim installieren von sqlite folgende Meldung:

pi@raspberrypi:~ $ php -v
PHP 7.4.25 (cli) (built: Oct 23 2021 21:53:50) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.25, Copyright (c), by Zend Technologies
pi@raspberrypi:~ $ sudo apt install php7.4.25-sqlite
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package php7.4.25-sqlite
E: Couldn't find any package by glob 'php7.4.25-sqlite'

pi@raspberrypi:~ $ sudo apt install php7.x-sqlite3
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package php7.x-sqlite3
E: Couldn't find any package by glob 'php7.x-sqlite3'
Wo liegt das Problem? Bin genau nach Anleitung vorgegangen

**Comment by arevindh** [comment]
> Ich erhalte beim installieren von sqlite folgende Meldung:
> 
> pi@raspberrypi:~ $ php -v PHP 7.4.25 (cli) (built: Oct 23 2021 21:53:50) ( NTS ) Copyright (c) The PHP Group Zend Engine v3.4.0, Copyright (c) Zend Technologies with Zend OPcache v7.4.25, Copyright (c), by Zend Technologies pi@raspberrypi:~ $ sudo apt install php7.4.25-sqlite Reading package lists... Done Building dependency tree... Done Reading state information... Done E: Unable to locate package php7.4.25-sqlite E: Couldn't find any package by glob 'php7.4.25-sqlite'
> 
> pi@raspberrypi:~ $ sudo apt install php7.x-sqlite3 Reading package lists... Done Building dependency tree... Done Reading state information... Done E: Unable to locate package php7.x-sqlite3 E: Couldn't find any package by glob 'php7.x-sqlite3' Wo liegt das Problem? Bin genau nach Anleitung vorgegangen

Verwenden Sie einfach `sudo apt install php7.4-sqlite` . `.25` ist eine Nebenversion und wird nicht benötigt.

**Comment by xnetworker** [comment]
Das gleiche: 
`pi@raspberrypi:~ $ sudo apt install php7.4-sqlite
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package php7.4-sqlite
E: Couldn't find any package by glob 'php7.4-sqlite'
`

**Comment by arevindh** [comment]
> Das gleiche: pi@raspberrypi:~ $ sudo apt install php7.4-sqlite Reading package lists... Done Building dependency tree... Done Reading state information... Done E: Unable to locate package php7.4-sqlite E: Couldn't find any package by glob 'php7.4-sqlite'
Probier diese
`sudo apt install php7.4-sqlite3`

**Comment by xnetworker** [comment]
Jetzt erscheint kein Fehler:

pi@raspberrypi:~ $ sudo apt install php7.4-sqlite3
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
php7.4-sqlite3 is already the newest version (7.4.25-1+deb11u1).
php7.4-sqlite3 set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

RPI 4 + Raspbian OS light

**Comment by arevindh** [comment]
> Jetzt erscheint kein Fehler:

Scheint bereits installiert zu sein, können Sie mit dem nächsten Schritt fortfahren.

**Comment by xnetworker** [comment]
klappt. Vielen Dank
