### ISSUE TITLE
Star Trek LCARS theme (dark) Support

### ISSUE THREAD

**Issue by town3r** [arevindh/pihole-speedtest#106]
If only the dashboard graph for Speedtest matched the others in the `Star Trek LCARS theme (dark)` theme.

![image](https://user-images.githubusercontent.com/12396203/154284683-97949174-03b6-473e-81f0-6b0be74b5e14.png)

_Originally posted by @town3r in https://github.com/arevindh/pihole-speedtest/issues/105#issuecomment-1041545391_

**Comment by arevindh** [comment]
@town3r What colors do you prefer for this theme?

**Comment by arevindh** [comment]
![image](https://user-images.githubusercontent.com/693151/154845099-216a2941-1174-4051-b3ae-61222233db3e.png)
@town3r  Like this ?

**Comment by town3r** [comment]
Ohh that looks great!

**Comment by arevindh** [comment]
@town3r can you update and check?

**Comment by town3r** [comment]
Looks good.

Only think I'd say is the spacing between at the bottom seems a bit much.

Would also be cool if the graph could have likes for every hour if range is small enough like the last 24 hours setting. 

![image](https://user-images.githubusercontent.com/12396203/155025799-7bde7f81-13a9-44da-89ee-4a0b667b064b.png)
