### ISSUE TITLE
Problem with displaying the correctly web version(AdminLTE) of pi-hole when using PADD and speedtest mod

### ISSUE THREAD

**Issue by Falconcrest** [arevindh/pihole-speedtest#107]
Hello, 

first of all the speedtest mod is a small, but nice feature for pi-hole. 
Unfortunately, I personally have a problem with it. I also use PADD and after installing the mod, I see another web version of pi-hole.
In my current case it is version 5.11.1 and no longer 5.11 as in the original.
PADD therefore warns: updates are available.
It's only a "cosmetic" problem, I know I've changed something, but isn't there a more elegant solution?

**Comment by arevindh** [comment]
@Falconcrest try updating both, let me know if it fixes the issue. 
5.11.1 is released due to a major change in speedtest mod codebase.

**Comment by Falconcrest** [comment]
@arevindh Did I understand you correctly, I should update PADD and Speedtest mod again?
But Pi-Hole and PADD were up to date when I installed the last version of speedtest mod!

**Comment by arevindh** [comment]
@Falconcrest yes, please try it 
https://github.com/arevindh/pihole-speedtest/wiki/Updating--Speedtest-Mod

**Comment by arevindh** [comment]
@Falconcrest Found the issue, working on it.

**Comment by arevindh** [comment]
@Falconcrest try this
```
sudo su
cd /opt/pihole/
rm version.sh
https://raw.githubusercontent.com/arevindh/pi-hole/master/advanced/Scripts/version.sh
chmod +x version.sh
rm /etc/pihole/GitHubVersions
sudo pihole -v -a
```

**Comment by Falconcrest** [comment]
@arevindh OK, it works. I still had to use wget, but now the display is correct. Is this a temporary fix that I then have to run every time? Thank you very much for your effort.

**Comment by arevindh** [comment]
@Falconcrest that's weird. How did you install pihole?
Anyway the issue will be fixed with next version for pihole front end

**Comment by Falconcrest** [comment]
@arevindh The system is DietPi, based on Debian. There you can select and install Pi-hole from a software pool. But ok, I'm waiting for the next version. Thanks!

**Comment by arevindh** [comment]
@Falconcrest seems like dietpi handles installs in their own way, thay might be just deleting the entire codebase and re downloading from git. You can try switching to normal installation using the bash script provided by pihole.

**Comment by Falconcrest** [comment]
@arevindh After installing the latest update from speedtest mod, the display in PADD and Pi-hole is even more confusing.

`root@pihole:~# pihole -v
  Pi-hole version is v5.9 (Latest: v5.9)
  AdminLTE version is v5.11.1-2-gf82e5843 (Latest: v5.11)
  FTL version is v5.14 (Latest: v5.14)`

Pi-hole® v5.9, Web v5.11.1-2-825843, FTL v5.14, PADD v3.6.6
[✓] Core  [✓] FTL   [i] Updates are available.

**Comment by arevindh** [comment]
Added more change today (Just published release today)
```
sudo su
cd /var/www/html/admin/
git pull
pihole updatechecker local
```

**Comment by Falconcrest** [comment]
@arevindh Yes, this only causes a temporary correction. After a reboot the status was back to the previous one.

But after running

`curl -sSL https://github.com/arevindh/pihole-speedtest/raw/master/update.sh | bash`

the display was almost correct again, except for the known issue with Web v5.11.1.

**Comment by arevindh** [comment]
@Falconcrest that will be fixed in the next release since.

**Comment by Falconcrest** [comment]
@arevindh Very good, I'll report then...

I also once made a request in the DietPi forum, maybe someone there has an idea.

**Comment by arevindh** [comment]
@Falconcrest Try this, I just deleted and created new tag

```
sudo su
cd /var/www/html/admin/
git tag -d v5.11
git fetch --tags
git pull
```

```
pihole updatechecker local
pihole -v -a
```

**Comment by arevindh** [comment]
> @arevindh Yes, this only causes a temporary correction. After a reboot the status was back to the previous one.
> 
> But after running
> 
> `curl -sSL https://github.com/arevindh/pihole-speedtest/raw/master/update.sh | bash`
> 
> the display was almost correct again, except for the known issue with Web v5.11.1.

Oops, you were using this update command, the command wasn't updated to fix this issue (the change was specifically for your use case ). Any way now I added it to the update script.

**Comment by town3r** [comment]
Not sure if this is related to the update you made but I’m getting the following when running the Update command.

```bash: line 45: https://raw.githubusercontent.com/arevindh/pi-hole/master/advanced/Scripts/version.sh: No such file or directory
chmod: cannot access 'version.sh': No such file or directory```

On Mar 17, 2022, at 8:38 AM, itsmesid ***@***.***> wrote:

﻿
@arevindh Yes, this only causes a temporary correction. After a reboot the status was back to the previous one.

But after running

curl -sSL https://github.com/arevindh/pihole-speedtest/raw/master/update.sh | bash

the display was almost correct again, except for the known issue with Web v5.11.1.

Oops, you were using this update command, the command wasn't updated to fix this issue (the change was specifically for your use case ). Anyway now I added it to the update script.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you are subscribed to this thread.

**Comment by Falconcrest** [comment]
@arevindh & @town3r 
Sorry, I had the same error too, I didn't mention it and then did some steps again manually.
I just ran the script again and it works correctly.

**Comment by arevindh** [comment]
Closing this issue
