### ISSUE TITLE
Export function measurement results

### ISSUE THREAD

**Issue by xnetworker** [arevindh/pihole-speedtest#108]
Is the option to integrate a function to export the measurement results into excel?

**Comment by arevindh** [comment]
@xnetworker 

```
sudo su
cd /var/www/html/admin/
git tag -d $(git tag -l)
git fetch --tags
git pull
git checkout csv-export
```
Open `http://<pihole-ip>/admin/api.php?csv-export=1` while after login (Also available from Speedtest tab). 

Will `not` be merged until the next release of pihole.

**Comment by arevindh** [comment]
Merged
