### ISSUE TITLE
nothing running in Pi-Hole

### ISSUE THREAD

**Issue by tehmessiah75** [arevindh/pihole-speedtest#113]
Hi,
I just did a fresh install on a new SD card and I can see the graph and have successfully ran a speed test in CMDLINE but nothing is running automatically.
I set it to run every hour and display the graph in weekly format but it has been running for 2hrs but the only result in the graph is my CMDLINE test.

**Comment by arevindh** [comment]
@tehmessiah75 which os are you using?

**Comment by arevindh** [comment]
Also the results of

sudo -u root crontab -e

**Comment by tehmessiah75** [comment]
I am using raspbian lite Bullseye 32bit

sudo -u root crontab -e
0 */1 * * * sudo "/var/www/html/admin/scripts/pi-hole/speedtest/speedtest-official.sh"  > /dev/null 2>&1

I think I discovered the issue though. I missed a step where I have to change it from Python to cmdline :/
I'm just waiting for 10 min for the next hour to tick over.

For the Crontab would I put "30 * * * * "Blah" for it to run every 30 minutes?

**Comment by arevindh** [comment]
> I am using raspbian lite Bullseye 32bit
> 
> sudo -u root crontab -e 0 */1 * * * sudo "/var/www/html/admin/scripts/pi-hole/speedtest/speedtest-official.sh" > /dev/null 2>&1
> 
> I think I discovered the issue though. I missed a step where I have to change it from Python to cmdline :/ I'm just waiting for 10 min for the next hour to tick over.
> 
> For the Crontab would I put "30 * * * * "Blah" for it to run every 30 minutes?

Check https://github.com/arevindh/pihole-speedtest/issues/90
