### ISSUE TITLE
Pi-hole v5.11.4 FTL v5.16.3 Web Interface v5.13 (FTL v5.16.3 upgrade is available)

### ISSUE THREAD

**Issue by corasaniti** [arevindh/pihole-speedtest#115]
Hi, @arevindh 

Pi-hole v5.11.4 FTL v5.16.3 Web Interface v5.13 and FTL v5.16.3 upgrade is available...
when are you able to upgrade? 
Thanks in advance

**Comment by arevindh** [comment]
@corasaniti did a fresh win11 install, I need to set up a few things. I will update it in 2 days.

**Comment by SHelfinger** [comment]
`pihole up`

Should do the job, since FTL has nothing to do with speed test mod ;)

**Comment by corasaniti** [comment]
@arevindh 
Thanks I'll wait a few days

@SHelfinger 
No pihole -up doesn't work in a Docker containerI'll wait a few days

**Comment by corasaniti** [comment]
@arevindh 
You may also include the DockerTag in your build :-)

**Comment by arevindh** [comment]
> @arevindh You may also include the DockerTag in your build :-)

Can you try image `arevindh/pihole:2022.08.2`

**Comment by arevindh** [comment]
@corasaniti are you interested in testing one of my other projects? 

https://hub.docker.com/r/arevindh/homelab-tracker

**Comment by corasaniti** [comment]
@arevindh 
Thanks this morning I will try it and let you know. 
I will also try homelab-tracker 
thanks again
:-)

**Comment by corasaniti** [comment]
@arevindh 
The tag `2002.08.2` seems to work correctly. . 
I keep it monitored for a few days. In the meantime I have kept the old tag `2022.07.2` which I will then delete.
I'll let you know in a few days, so you can push the tag `2022.08.2` on the `latest `...
Thanks
PC

**Comment by corasaniti** [comment]
I'm sorry to inform you that the new `docker tag 2022.08.3` has been released.
You should do a new build :-(
Thank you

**Comment by arevindh** [comment]
@arevindh check 2022.08.3

**Comment by corasaniti** [comment]
@arevindh 
It works perfectly. 
Wait a few days to make sure a new tag is not released and then you can push the tag `2022.08.3` to the last branch
Thanks

**Comment by corasaniti** [comment]
A new tag `2022.09.1` is now available :-( 
Sorry but you should do a new build
Thanks

**Comment by arevindh** [comment]
@corasaniti build is already there, just try it and let me know if everything is fine

**Comment by arevindh** [comment]
> A new tag `2022.09.1` is now available :-( Sorry but you should do a new build Thanks

https://hub.docker.com/layers/arevindh/pihole/2022.09.1/images/sha256-d768bb9167f0da0322d580b17ef225aa6423fe9626baa0b1e0e418ac028ef668?context=repo

**Comment by corasaniti** [comment]
Unfortunately A new tag `2022.09.2` is now available :-( 
[https://hub.docker.com/layers/pihole/pihole/2022.09.2/images/sha256-533523ece86c4b45d0944c754e31521f8dd1e904da12531bfc0e46ff241ae721?context=explore](url)
Sorry but you should do a new build 
Thanks

**Comment by corasaniti** [comment]
@arevindh 
Hi, sorry I saw you updated to the version.

`Pi-hole v5.12 FTL v5.17 Web Interface v5.14.2`

However it would be better if you created the new `2022.09.2` tag because the older versions are included in the `20222.09.2` tag so you don't get confused. 
Alternatively you could push that version to the last branch.
Thanks

**Comment by arevindh** [comment]
> @arevindh 
> Hi, sorry I saw you updated to the version.
> 
> `Pi-hole v5.12 FTL v5.17 Web Interface v5.14.2`
> 
> However it would be better if you created the new `2022.09.2` tag because the older versions are included in the `20222.09.2` tag so you don't get confused. 
> Alternatively you could push that version to the last branch.
> Thanks
> 

Already Updated to the existing version, since they may release new one.
Btw please create a new ticket instead of closed ones.
