### ISSUE TITLE
Pi-hole 5.12/FTL 5.17/Web 5.14.1 released today

### ISSUE THREAD

**Issue by ChrisWNY** [arevindh/pihole-speedtest#116]
https://github.com/pi-hole/AdminLTE/releases/tag/v5.14.1 - ADMIN LTE

https://github.com/pi-hole/pi-hole/releases/tag/v5.12 - Pi-Hole core

https://github.com/pi-hole/FTL/releases/tag/v5.17 - FTL v5.17

**Comment by arevindh** [comment]
Thats a lot of conflicts 😞 
![image](https://user-images.githubusercontent.com/693151/188259200-aea5843d-00eb-40e0-a44b-38bd387ffc5d.png)

**Comment by ChrisWNY** [comment]
I thought about that when I read the changelog...lots of changes to the Pi-hole AdminLTE in the latest update.

**Comment by arevindh** [comment]
@ChrisWNY can you try updating ?

**Comment by ChrisWNY** [comment]
Looks good - updated, but now pi-hole is up to Admin LTE 5.14.2. 

https://github.com/pi-hole/AdminLTE/releases/tag/v5.14.2

This time the change log is much smaller.

**Comment by arevindh** [comment]
@ChrisWNY can you try updating?

**Comment by arevindh** [comment]
> Just pulled the update manually -
> 
> I'm getting this for the version of the Admin LTE from pihole -v:
> 
> AdminLTE version is v5.14.1-305-g77b3faff (Latest: v5.14.2)

Try this `pihole updatechecker local`

**Comment by ChrisWNY** [comment]
Same result - I have a local script I use to update (just has the commands on your website), pihole updatechecker local is always the last command run after the update is pulled.

**Comment by ChrisWNY** [comment]
Just re-ran the update script and it looks like everything is good to go!

**Comment by ChrisWNY** [comment]
I'll close this one - thanks for the quick updates as always!
