### ISSUE TITLE
Tags and versions Alignment with official Pihole

### ISSUE THREAD

**Issue by corasaniti** [arevindh/pihole-speedtest#118]
@arevindh 

Hi, the latest updated versions `Pi-hole v5.12 FTL v5.17 Web Interface v5.14.2` are included in the docker `tag 2022.09.2`, while you build them inside the `tag 2022.09.1`.

You should replace the `tag 2022.09.1` with the latest official available `2022.09.2` in order not to get confused, or create a new `tag  2022.09.2` with the latest versions already released.
Thanks

**Comment by arevindh** [comment]
@corasaniti created a new build for `2022.09.2` with tag `dev-2022.09.2` 
Let me know if its good for release
