### ISSUE TITLE
speedtest: error: unrecognized arguments: --accept-gdpr --accept-license -f json-pretty

### ISSUE THREAD

**Issue by amgsys75** [arevindh/pihole-speedtest#120]
Hi,
running last command
sudo "/var/www/html/admin/scripts/pi-hole/speedtest/speedtest-official.sh" 
create an error 
speedtest: error: unrecognized arguments: --accept-gdpr --accept-license -f json-pretty
using speedtest-cli 2.1.2, pihole on linux mint

**Comment by arevindh** [comment]
@amgsys75 is it a fresh install?

**Comment by arevindh** [comment]
@amgsys75 please remove python based speedtest  

Steps here : https://github.com/arevindh/pihole-speedtest/wiki/Installing-Speedtest-Mod#remove-python-cli

**Comment by amgsys75** [comment]
yes, its fresh install ...
i managed to remove it and install older version, it works
https://install.speedtest.net/app/cli/ookla-speedtest-1.2.0-linux-x86_64.tgz
using this version

**Comment by arevindh** [comment]
> yes, its fresh install ...
> i managed to remove it and install older version, it works
> https://install.speedtest.net/app/cli/ookla-speedtest-1.2.0-linux-x86_64.tgz
> using this version 

This is the latest version
