### ISSUE TITLE
Another new Pi-hole release...

### ISSUE THREAD

**Issue by ChrisWNY** [arevindh/pihole-speedtest#121]
Pi-hole 5.12.2 - https://github.com/pi-hole/pi-hole/releases/tag/v5.12.2
FTL 5.18.1 - https://github.com/pi-hole/FTL/releases/tag/v5.18.1
Admin LTE 5.15.1 - https://github.com/pi-hole/AdminLTE/releases/v5.15.1

Another point release for Pi-hole.

**Comment by arevindh** [comment]
Let me try this week.

**Comment by arevindh** [comment]
@ChrisWNY Updated

**Comment by ChrisWNY** [comment]
Awesome...I will grab the latest repo and report back shortly. Thanks!

**Comment by ChrisWNY** [comment]
Seems to be working - tested the speedtest script, etc. UI looks good, version info is correct. Thanks again! Will close this out.
