### ISSUE TITLE
Pi-hole FTL v5.18.2, Web v5.16 and Core v5.13 released

### ISSUE THREAD

**Issue by ChrisWNY** [arevindh/pihole-speedtest#122]
Another new release...been busy the past month with new Pi-hole releases...

https://pi-hole.net/blog/2022/10/10/pi-hole-ftl-v5-18-2-web-v5-16-and-core-v5-13-released#page-content

**Comment by arevindh** [comment]
@ChrisWNY I will try to do it in a few days.

**Comment by arevindh** [comment]
@ChrisWNY Updated , please check

**Comment by ChrisWNY** [comment]
Downloaded the new admin repo, everything looks good. Thanks, Sid! I'll close this one out.
