### ISSUE TITLE
FHL Error

### ISSUE THREAD

**Issue by chiragnahata** [arevindh/pihole-speedtest#123]
https://discourse.pi-hole.net/t/pihole-ftl-error/58565

**Comment by arevindh** [comment]
@chiragnahata can you try to update it? 

https://github.com/arevindh/pihole-speedtest/wiki/Updating--Speedtest-Mod

**Comment by arevindh** [comment]
@chiragnahata any updates?

**Comment by chiragnahata** [comment]
> @chiragnahata any updates? 
> 

Same issue

**Comment by chiragnahata** [comment]
> @chiragnahata 
> 
> Wait till the mod is updated for latest version and try
> 
> https://github.com/arevindh/pihole-speedtest/wiki/Updating--Speedtest-Mod

??

**Comment by arevindh** [comment]
> > @chiragnahata 
> > 
> > Wait till the mod is updated for latest version and try
> > 
> > https://github.com/arevindh/pihole-speedtest/wiki/Updating--Speedtest-Mod
> 
> ??

Mod was updated on the same day.

Use the steps from the link in quoted reply to update .

If nothing is working try uninstalling the mod 

https://github.com/arevindh/pihole-speedtest/wiki/Uninstalling-Speedtest-Mod
