### ISSUE TITLE
Another new Pi-hole Update - 5.14.1/5.19.1/5.17

### ISSUE THREAD

**Issue by ChrisWNY** [arevindh/pihole-speedtest#124]
Web interface has been updated to 5.17. 

https://github.com/pi-hole/AdminLTE/releases/v5.17

**Comment by arevindh** [comment]
@ChrisWNY will try to update by tomorrow

**Comment by ChrisWNY** [comment]
FTL saw another update a few days ago...the web interface however remains at v5.17.

**Comment by arevindh** [comment]
@ChrisWNY updated yesterday, I forgot to mention it.

**Comment by ChrisWNY** [comment]
Looks good, Sid! I'll close this one out. Thanks!
