### ISSUE TITLE
No vertical axis on mobile

### ISSUE THREAD

**Issue by ipitio** [arevindh/pihole-speedtest#125]
![image](https://user-images.githubusercontent.com/21136719/204110416-849f2247-103f-4eea-90e0-a631c6b1c076.jpeg)

I use Safari on mobile, and the graph is flat as can be seen in the above image. It looks fine on desktop.

This bug was introduced in the previous update.

**Comment by SHelfinger** [comment]
Hello,

yes I can confirm, to solve the issue in the file

/var/www/html/admin/index.php

Change the line 124 from

`<html>
<body>


<div class="chart">
--
  | <canvas id="speedtestChart" width="800" height="240"></canvas>
  | </div>


</body>
</html>`

to 

`<div class="chart" style="width: 100%; height: 180px">
                         <canvas id="speedtestChart"></canvas>
                     </div>`

Pihole changed the initial "chart" size with style attributes.

**Comment by ipitio** [comment]
I fixed the issue, along with some others (see above PR). Now I wanna see if I can bring back the bars...

[](https://user-images.githubusercontent.com/21136719/212462820-d4216a39-84f4-4be6-8702-351da54a5072.jpeg)

You can clone my fork in the meantime.
