### ISSUE TITLE
Another Pi-Hole Update - released Jan 16 2023

### ISSUE THREAD

**Issue by ChrisWNY** [arevindh/pihole-speedtest#128]
Pi-hole v5.15/FTL 5.20/Web 5.18.1

https://github.com/pi-hole/pi-hole/releases/tag/v5.15

**Comment by arevindh** [comment]
Will update this week

**Comment by arevindh** [comment]
Updated to the latest version, but @ipitio is working on a few quality-of-life updates.

**Comment by ChrisWNY** [comment]
Just ran my updater script...things look good! Will look forward to the quality-of-life updates! Thanks!
