### ISSUE TITLE
alerting

### ISSUE THREAD

**Issue by Joshuaharry120** [arevindh/pihole-speedtest#129]
Hi,

Is there a way to have an alert setup, for example, if my speed drops less then X AMT, after a few retrys it will send a webhook request or somewhere within the code to be able to put my own code in to trigger an SMS?

an Example how i would see it work(my internet speed is 1gb down, 100 up )

Speedtest is ran, Speed is 50mpbs, waits 30 seconds, runs another test, speed is 50 or below a set amt, runs a final test, is below a set amt, triggers a webhook or option within the code to run my own alert code?

Josh

Apologies if this is already a thing and repeating work.

**Comment by Joshuaharry120** [comment]
Another question: after a standard test is completed, where is the speedtest data stored?

**Comment by ipitio** [comment]
The data is stored at `/etc/pihole/speedtest.db`, you could just monitor that.

**Comment by SHelfinger** [comment]
For example, my porn notifier. (Have a hotspot system)

[GIST PiHole-FTL-noty.php](https://gist.github.com/SHelfinger/ad714e7f19b0eafba2d7fed793e51ea4)

**Comment by arevindh** [comment]
> Hi,
> 
> Is there a way to have an alert setup, for example, if my speed drops less then X AMT, after a few retrys it will send a webhook request or somewhere within the code to be able to put my own code in to trigger an SMS?
> 
> an Example how i would see it work(my internet speed is 1gb down, 100 up )
> 
> Speedtest is ran, Speed is 50mpbs, waits 30 seconds, runs another test, speed is 50 or below a set amt, runs a final test, is below a set amt, triggers a webhook or option within the code to run my own alert code?
> 
> Josh
> 
> Apologies if this is already a thing and repeating work.

I am checking some of the possibilities, will respond once completed.
