### ISSUE TITLE
Missing updates after Docker Tag 2022.09.4

### ISSUE THREAD

**Issue by corasaniti** [arevindh/pihole-speedtest#131]
Hi,

I'm sorry not to see more updates your very interesting project. 
You are stopped at Docker Tag 2022.09.4 and we have arrived at Docker Tag 2023.01.6
Thank you

**Comment by arevindh** [comment]
try `arevindh/pihole:2023.01.9-dev` 
Is there any way you could switch to the normal version of pi-hole? It is becoming more difficult to build and test.
