### ISSUE TITLE
Can I run Pi-Hole Speedtest on Read Only file system?

### ISSUE THREAD

**Issue by tehmessiah75** [arevindh/pihole-speedtest#132]
Sorry in advance, I dont know where to ask questions so I'm doing it here.
In order to extend the life of my sd card I have enabled the Read Only File system in raspi-config.
Can I still use the Pi-Hole Speed Test  in ROFS?
thanks in advance
Ben

**Comment by SHelfinger** [comment]
Yes possible. Just put the DB files in RAM.

Location 
```
/etc/pihole/speedtest.db
/etc/pihole/pihole-FTL.db
```

The files can be also moved to other locations by doing so via the config file.

**Comment by tehmessiah75** [comment]
Is that where I need to move them to?
If not, how do I move them to RAM?

Thank you

**Comment by SHelfinger** [comment]
How did you setup your ROFS?

If /etc/pihole/ is already in RAM. You don't need to do anything, since gravity.db, pihole-FTL.db and speedtest.db are in RAM.

**Comment by arevindh** [comment]
Stale issue
