### ISSUE TITLE
New Pi-hole releases

### ISSUE THREAD

**Issue by ChrisWNY** [arevindh/pihole-speedtest#134]
Pi-hole 5.15.2 released today, web is 5.18.2, doesn't appear to be a substantial release over the previous version...

https://github.com/pi-hole/AdminLTE/releases/v5.18.2

**Comment by arevindh** [comment]
@ChrisWNY already is testing

**Comment by arevindh** [comment]
Seems like they released another update 5 hours ago 😶‍.

**Comment by arevindh** [comment]
5.18.3 is lastest one 6 hours ago

**Comment by cronus130** [comment]
Another new update: Pi-hole [v5.15.5] FTL [v5.21] Web Interface [v5.18.4]

**Comment by arevindh** [comment]
@ChrisWNY @cronus130 updated to the new version with an installer and more things added by @ipitio

**Comment by ChrisWNY** [comment]
I'm getting a blank for the graph generated on the main pi-hole page, but the speedtest history is still fine from the left-hand menu, and the settings show up just fine. I tried to re-install from the new settings page and no dice.

**Comment by town3r** [comment]
> I'm getting a blank for the graph generated on the main pi-hole page, but the speedtest history is still fine from the left-hand menu, and the settings show up just fine. I tried to re-install from the new settings page and no dice.

Experiencing the same thing

**Comment by arevindh** [comment]
@ChrisWNY @town3r what about console errors?

**Comment by flipptx** [comment]
when i run the update i get this....

pi@pi-hole:~ $ curl -sSLN https://github.com/arevindh/pihole-speedtest/raw/master/mod.sh | sudo bash -s up
Thanks for using Speedtest Mod!
Script by @ipitio

Sat 11 Feb 19:01:16 CST 2023 - Verifying Dependencies...
Sat 11 Feb 19:01:16 CST 2023 - Adding speedtest source...
main: line 33: UBUNTU_CODENAME: unbound variable
Sat 11 Feb 19:01:16 CST 2023 - Process Aborted
Sat 11 Feb 19:01:16 CST 2023 - A restore is not needed or one failed.
Sat 11 Feb 19:01:16 CST 2023 - Please try again or try manually.

**Comment by ipitio** [comment]
oops https://github.com/arevindh/pihole-speedtest/pull/135

**Comment by ChrisWNY** [comment]
I run 

> when i run the update i get this....
> 
> pi@pi-hole:~ $ curl -sSLN https://github.com/arevindh/pihole-speedtest/raw/master/mod.sh | sudo bash -s up Thanks for using Speedtest Mod! Script by @ipitio
> 
> Sat 11 Feb 19:01:16 CST 2023 - Verifying Dependencies... Sat 11 Feb 19:01:16 CST 2023 - Adding speedtest source... main: line 33: UBUNTU_CODENAME: unbound variable Sat 11 Feb 19:01:16 CST 2023 - Process Aborted Sat 11 Feb 19:01:16 CST 2023 - A restore is not needed or one failed. Sat 11 Feb 19:01:16 CST 2023 - Please try again or try manually.

I have the exact same problem running the script.

**Comment by arevindh** [comment]
@ChrisWNY @flipptx can you guys try the old method for now

**Comment by flipptx** [comment]
Whats the “old method” ?

 

From: itsmesid ***@***.***>
Reply-To: arevindh/pihole-speedtest ***@***.***>
Date: Saturday, February 11, 2023 at 9:30 PM
To: arevindh/pihole-speedtest ***@***.***>
Cc: flipptx ***@***.***>, Mention ***@***.***>
Subject: Re: [arevindh/pihole-speedtest] New Pi-hole releases (Issue #134)

 

@ChrisWNY @flipptx can you guys try the old method for now

**Comment by arevindh** [comment]
> Whats the “old method” ? From: itsmesid ***@***.***> Reply-To: arevindh/pihole-speedtest ***@***.***> Date: Saturday, February 11, 2023 at 9:30 PM To: arevindh/pihole-speedtest ***@***.***> Cc: flipptx ***@***.***>, Mention ***@***.***> Subject: Re: [arevindh/pihole-speedtest] New Pi-hole releases (Issue #134) @ChrisWNY @flipptx can you guys try the old method for now — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***>

https://github.com/arevindh/pihole-speedtest/wiki/Updating--Speedtest-Mod

**Comment by ChrisWNY** [comment]
I can confirm it's working properly now.

**Comment by arevindh** [comment]
> I can confirm it's working properly now.

Try changing the schedule and confirm that it is working.

**Comment by ChrisWNY** [comment]
I changed the testing interval a couple of times and no issues with the script launching and the UI updating.

**Comment by flipptx** [comment]
using the manual method i was able to update

**Comment by ChrisWNY** [comment]
Closing as the manual update worked.
