### ISSUE TITLE
Another new Pi-hole release - v5.17

### ISSUE THREAD

**Issue by ChrisWNY** [arevindh/pihole-speedtest#143]
https://github.com/pi-hole/pi-hole/releases/tag/v5.17

Web interface -
https://github.com/pi-hole/AdminLTE/releases/tag/v5.20.1

**Comment by cronus130** [comment]
Another minor core update today to:  v5.17.1 https://github.com/pi-hole/pi-hole/releases/v5.17.1

**Comment by arevindh** [comment]
It seems like there is a major issue that needs to be addressed, I will update after it is complete.
@ChrisWNY @cronus130

**Comment by arevindh** [comment]
Updated

**Comment by ChrisWNY** [comment]
Closed - updated.
