### ISSUE TITLE
Error installing through script

### ISSUE THREAD

**Issue by paradox-sp** [arevindh/pihole-speedtest#144]
Thanks for using Speedtest Mod!
Script by @ipitio

- Verifying Dependencies...
 - Adding speedtest source...
main: line 31: ID_LIKE: unbound variable
 - Process Aborted
main: line 182: $1: unbound variable

**Comment by arevindh** [comment]
@paradox-sp can you try the fix suggested by @ipitio 

`curl -sSLN https://raw.githubusercontent.com/ipitio/pihole-speedtest/debian/mod.sh | sudo bash`

**Comment by paradox-sp** [comment]
Worked perfectly. Thanks !!
