### ISSUE TITLE
Clear History doesn't seem to work

### ISSUE THREAD

**Issue by vasundhar** [arevindh/pihole-speedtest#146]
Clear history doesn't do anything and it might keep bloating if there is no limit on number of days you want to keep the history. 
Also when there is manual intervention, it says history will be cleared but nothing seem to happen. If something happens when will it happen ?

**Comment by arevindh** [comment]
Can you try `sudo pihole -a -sc` from terminal ?

**Comment by vasundhar** [comment]
pihole -a -sc works successfully. 
are you copying from '/var/www/html/admin/scripts/pi-hole/speedtest/speedtest.db' to /etc/pihole/speedtest.db with that ?

**Comment by arevindh** [comment]
> pihole -a -sc works successfully. are you copying from '/var/www/html/admin/scripts/pi-hole/speedtest/speedtest.db' to /etc/pihole/speedtest.db with that ?

Yes
