### ISSUE TITLE
Speedtest Returns "No Internet Connection"

### ISSUE THREAD

**Issue by meAT9EWk** [arevindh/pihole-speedtest#149]
Problem: Pihole-Speedtest returns "No Internet". Speedtest runs via terminal. Speedtest returns "sudo: /var/www/html/admin/scripts/pi-hole/speedtest/speedtest-official.sh: command not found" when run using the command

`sudo "/var/www/html/admin/scripts/pi-hole/speedtest/speedtest-official.sh" `

Additionally, manually setting Speedtest.net Server via list id fails to change behavior.

Troubleshooting steps: removed and reinstalled Pihole-Speedtest using both Ookla speedtest version 1.0 and 1.2. Current version is 1.2.0.84.

**Comment by arevindh** [comment]
> Problem: Pihole-Speedtest returns "No Internet". Speedtest runs via terminal. Speedtest returns "sudo: /var/www/html/admin/scripts/pi-hole/speedtest/speedtest-official.sh: command not found" when run using the command
> 
> `sudo "/var/www/html/admin/scripts/pi-hole/speedtest/speedtest-official.sh" `
> 
> Additionally, manually setting Speedtest.net Server via list id fails to change behavior.
> 
> Troubleshooting steps: removed and reinstalled Pihole-Speedtest using both Ookla speedtest version 1.0 and 1.2. Current version is 1.2.0.84.

Whats the output of `speedtest` ?

**Comment by meAT9EWk** [comment]
> Whats the output of `speedtest` ?

~$ speedtest
Speedtest by Ookla
Server: Tele-Page, Inc. - Oneida, TN (id: 38054)
ISP: AT&T Internet
Idle Latency:    18.84 ms   (jitter: 0.70ms, low: 17.99ms, high: 19.35ms)
Download:   939.95 Mbps (data used: 995.0 MB)                               
            32.23 ms   (jitter: 1.80ms, low: 18.47ms, high: 50.66ms)
Upload:   937.90 Mbps (data used: 1.1 GB)                                 
            22.91 ms   (jitter: 1.67ms, low: 16.65ms, high: 32.16ms)
Packet Loss:     0.0%
Result URL: https://www.speedtest.net/result/c/e553afcc-5982-44f8-b5ce-69c5215e9ea8

**Comment by arevindh** [comment]
Does running `sudo "/var/www/html/admin/scripts/pi-hole/speedtest/speedtest-official.sh"` show any error line numbers?

**Comment by meAT9EWk** [comment]
sudo "/var/www/html/admin/scripts/pi-hole/speedtest/speedtest-official.sh"
sudo: /var/www/html/admin/scripts/pi-hole/speedtest/speedtest-official.sh: command not found'

And in that directory, there's only 
/var/www/html/admin/scripts/pi-hole/speedtest $ dir
speedtest.db  speedtest.sh  uninstall.sh

**Comment by arevindh** [comment]
> sudo "/var/www/html/admin/scripts/pi-hole/speedtest/speedtest-official.sh"
> sudo: /var/www/html/admin/scripts/pi-hole/speedtest/speedtest-official.sh: command not found'
> 
> And in that directory, there's only 
> /var/www/html/admin/scripts/pi-hole/speedtest $ dir
> speedtest.db  speedtest.sh  uninstall.sh

Seems like the doc is not updated , fa you try the existing one ?

**Comment by meAT9EWk** [comment]
$ sudo "/var/www/html/admin/scripts/pi-hole/speedtest/speedtest.sh"
Test has been initiated, please wait.
[2023-12-09 18:16:39.811] [error] Configuration - Specified invalid server ID number (InvalidServerId)
[2023-12-09 18:16:39.843] [error] Configuration - Specified invalid server ID number (InvalidServerId)
No Internet

**Comment by arevindh** [comment]
> $ sudo "/var/www/html/admin/scripts/pi-hole/speedtest/speedtest.sh" Test has been initiated, please wait. [2023-12-09 18:16:39.811] [error] Configuration - Specified invalid server ID number (InvalidServerId) [2023-12-09 18:16:39.843] [error] Configuration - Specified invalid server ID number (InvalidServerId) No Internet

Can you post the output of  `whereis speedtest`

**Comment by arevindh** [comment]
Also hope you have done this step :  https://github.com/arevindh/pihole-speedtest/wiki/Installing-Speedtest-Mod#install-speedtest-cli

**Comment by meAT9EWk** [comment]
~ $ whereis speedtest
speedtest: /usr/bin/speedtest

Specifying a server using ~ $ speedtest --server-id=38054 returns expected speedtest results. Specifying the server in the web GUI does not save in the GUI or result in behavior change when running `sudo "/var/www/html/admin/scripts/pi-hole/speedtest/speedtest.sh:"`.

Reinstalling the older version of speedtest-cli (1.0.0.2) results in no change in behavior, but still successfully runs from command line.
