### ISSUE TITLE
one liner install does not work 

### ISSUE THREAD

**Issue by chivarpilones** [arevindh/pihole-speedtest#150]
chivar@Phr0zen:~ $ sudo curl -sSLN https://github.com/arevindh/pihole-speedtest/raw/master/mod.sh | sudo bash
Thanks for using Speedtest Mod!
Script by @ipitio

Thu 11 Jan 13:48:32 PST 2024 - Verifying Dependencies...
Reading package lists...
Building dependency tree...
Reading state information...
Package 'speedtest-cli' is not installed, so not removed
sqlite3 is already the newest version (3.40.1-2).
php8.2-sqlite3 is already the newest version (8.2.7-1~deb12u1).
jq is already the newest version (1.6-2.1).
speedtest is already the newest version (1.2.0.84-1.ea6b6773cf).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Thu 11 Jan 13:48:33 PST 2024 - Downloading Latest Speedtest Mod...
Cloning into 'new_admin'...
Note: switching to 'v5.21'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at f786329f Merge pull request #82 from arevindh/dev-v5.21
Cloning into 'new_pihole'...
Note: switching to 'v5.17.2'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at d189ef68 Merge pull request #65 from arevindh/dev-5.17.2
Thu 11 Jan 13:49:04 PST 2024 - Restoring Pi-hole...
Cloning into 'org_pihole'...
Cloning into 'org_admin'...
Thu 11 Jan 13:49:28 PST 2024 - Process Aborted
Thu 11 Jan 13:49:28 PST 2024 - Restoring Files...
Thu 11 Jan 13:49:28 PST 2024 - Files Restored
Thu 11 Jan 13:49:28 PST 2024 - Please try again or try manually.

**Comment by ipitio** [comment]
@chivarpilones Could you try running the change from my repo? 

    curl -sSLN https://github.com/ipitio/pihole-speedtest/raw/ipitio/mod.sh | sudo bash -s up

**Comment by chivarpilones** [comment]
chivar@Phr0z3n-Sven:~ $ sudo curl -sSLN https://github.com/ipitio/pihole-speedtest/raw/ipitio/mod.sh | sudo bash -s up
Thanks for using Speedtest Mod!
Script by @ipitio

Thu 11 Jan 22:25:37 PST 2024 - Verifying Dependencies...
Reading package lists...
Building dependency tree...
Reading state information...
Package 'speedtest-cli' is not installed, so not removed
sqlite3 is already the newest version (3.40.1-2).
php8.2-sqlite3 is already the newest version (8.2.7-1~deb12u1).
jq is already the newest version (1.6-2.1).
speedtest is already the newest version (1.2.0.84-1.ea6b6773cf).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Thu 11 Jan 22:25:40 PST 2024 - Downloading Latest Speedtest Mod...
Cloning into 'new_admin'...
Cloning into 'new_pihole'...
Thu 11 Jan 22:26:17 PST 2024 - Restoring Pi-hole...
Cloning into 'org_pihole'...
Cloning into 'org_admin'...
Thu 11 Jan 22:26:59 PST 2024 - Process Aborted
Thu 11 Jan 22:26:59 PST 2024 - A restore is not needed or one failed.
Thu 11 Jan 22:27:00 PST 2024 - Please try again or try manually.

**Comment by chivarpilones** [comment]
fresh install raspi os bookworm debian 12

curl -sSLN https://github.com/ipitio/pihole-speedtest/raw/ipitio/mod.sh | sudo bash -s up
Thanks for using Speedtest Mod!
Script by @ipitio

Sat 13 Jan 16:55:41 PST 2024 - Verifying Dependencies...
Sat 13 Jan 16:55:41 PST 2024 - Adding speedtest source...
Detected operating system as debian/bookworm.
Checking for curl...
Detected curl...
Checking for gpg...
Detected gpg...
Detected apt version as 2.6.1
Running apt-get update... done.
Installing debian-archive-keyring which is needed for installing 
apt-transport-https on many Debian systems.
Installing apt-transport-https... done.
Installing /etc/apt/sources.list.d/ookla_speedtest-cli.list...done.
Importing packagecloud gpg key... Packagecloud gpg key imported to /etc/apt/keyrings/ookla_speedtest-cli-archive-keyring.gpg
done.
Running apt-get update... done.

The repository is setup! You can now install packages.
Reading package lists...
Building dependency tree...
Reading state information...
Package 'speedtest-cli' is not installed, so not removed
php8.2-sqlite3 is already the newest version (8.2.7-1~deb12u1).
php8.2-sqlite3 set to manually installed.
jq is already the newest version (1.6-2.1).
jq set to manually installed.
Suggested packages:
  sqlite3-doc
The following NEW packages will be installed:
  speedtest sqlite3
0 upgraded, 2 newly installed, 0 to remove and 1 not upgraded.
Need to get 1,423 kB of archives.
After this operation, 3,127 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian bookworm/main arm64 sqlite3 arm64 3.40.1-2 [341 kB]
Get:2 https://packagecloud.io/ookla/speedtest-cli/debian bookworm/main arm64 speedtest arm64 1.2.0.84-1.ea6b6773cf [1,081 kB]
Fetched 1,423 kB in 3s (429 kB/s)
Selecting previously unselected package sqlite3.
(Reading database ... 128132 files and directories currently installed.)
Preparing to unpack .../sqlite3_3.40.1-2_arm64.deb ...
Unpacking sqlite3 (3.40.1-2) ...
Selecting previously unselected package speedtest.
Preparing to unpack .../speedtest_1.2.0.84-1.ea6b6773cf_arm64.deb ...
Unpacking speedtest (1.2.0.84-1.ea6b6773cf) ...
Setting up speedtest (1.2.0.84-1.ea6b6773cf) ...
Setting up sqlite3 (3.40.1-2) ...
Processing triggers for man-db (2.11.2-2) ...
Sat 13 Jan 16:56:42 PST 2024 - Downloading Latest Speedtest Mod...
Cloning into 'new_admin'...
Cloning into 'new_pihole'...
Sat 13 Jan 16:58:03 PST 2024 - Restoring Pi-hole...
Cloning into 'org_pihole'...
Cloning into 'org_admin'...
Sat 13 Jan 16:58:39 PST 2024 - Process Aborted
Sat 13 Jan 16:58:39 PST 2024 - A restore is not needed or one failed.

**Comment by ipitio** [comment]
I added a couple echos to the script to see where exactly the script fails, could you run it again?

**Comment by chivarpilones** [comment]
> I added a couple echos to the script to see where exactly the script fails, could you run it again?

Hi ipitio, thanks for your prompt responses i was able to properly installed the speedtest mod now without any issues or problems 

 sudo su
root@Phr0zen-Tr0lls:/home/chivar# curl -sSLN https://github.com/arevindh/pihole-speedtest/raw/master/mod.sh | sudo bash
Thanks for using Speedtest Mod!
Script by @ipitio

Tue 16 Jan 22:36:03 PST 2024 - Verifying Dependencies...
Reading package lists...
Building dependency tree...
Reading state information...
Package 'speedtest-cli' is not installed, so not removed
sqlite3 is already the newest version (3.40.1-2).
php8.2-sqlite3 is already the newest version (8.2.7-1~deb12u1).
jq is already the newest version (1.6-2.1).
speedtest is already the newest version (1.2.0.84-1.ea6b6773cf).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Tue 16 Jan 22:36:08 PST 2024 - Downloading Latest Speedtest Mod...
Cloning into 'new_admin'...
Note: switching to 'v5.21'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at f786329f Merge pull request #82 from arevindh/dev-v5.21
Cloning into 'new_pihole'...
Note: switching to 'v5.17.2'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at d189ef68 Merge pull request #65 from arevindh/dev-5.17.2
Tue 16 Jan 22:37:05 PST 2024 - Restoring Pi-hole...
Tue 16 Jan 22:37:05 PST 2024 - Uninstalling Current Speedtest Mod...
Tue 16 Jan 22:37:05 PST 2024 - Uninstall Complete
Tue 16 Jan 22:37:05 PST 2024 - Installing Speedtest Mod...
Tue 16 Jan 22:37:14 PST 2024 - Install Complete
root@Phr0zen-Tr0lls:/home/chivar#

**Comment by ipitio** [comment]
The issue was a failed version check for the web interface after it was cloned. Since you ran the script with `-up`, as per my instruction, the clone did not get removed when the script aborted. So the next time you attempted to install, the script bypassed the clone and version check and completed successfully. This was caused by two things:

1. "AdminLTE" changed to "web" and
2. the script was "uninstalling" the mod when it wasn't even installed

That second point resulted in unnecessary clones during install (slowing install significantly), but helped debug the first point faster (thanks to you). #151 resolves both.

**Comment by chivarpilones** [comment]
there is another thing that happen when i was able to install the mod.,
  the data that is to be displayed in "Speedtest Result" at the dashboard
does not reflect realtime,
  the graph displays a few hours back late / delayed not "realtime".
  the speedtest log meanwhile has the proper logged time

**Comment by ipitio** [comment]
Could you send a sc of the speedtest chart along with one of the other charts and of the speedtest log? Have you modified your browser's time zone?

**Comment by ipitio** [comment]
Nvm I think I fixed it.

**Comment by ipitio** [comment]
Yep, everything seems to be working; if you want the fixes now you can get them from my repo again:

    curl -sSLN https://github.com/ipitio/pihole-speedtest/raw/ipitio/mod.sh | sudo bash -s up
