### ISSUE TITLE
[Feature request] Docker Container

### ISSUE THREAD

**Issue by corasaniti** [arevindh/pihole-speedtest#152]
It would be nice to have the Docker container as the first version of pihole-speedtest
Thanks in advance
PC

**Comment by ipitio** [comment]
Yeah, we could add an example compose file similar to https://github.com/pi-hole/docker-pi-hole/#quick-start

**Comment by corasaniti** [comment]
@arevindh 
Hii, Is there any hope of having a Docker with Pihole and the Mod included like we had for the first version?
Thank you

**Comment by ipitio** [comment]
There's hope, I have it mostly working.

**Comment by ipitio** [comment]
https://github.com/arevindh/pihole-speedtest/pull/157
