### ISSUE TITLE
"Start time" column shows "Invalid date" after pihole update

### ISSUE THREAD

**Issue by guygrinberger** [arevindh/pihole-speedtest#158]
after updating pihole using `pihole -up` no results are seen on the speedtest graph.
in the speedtest log I can see that the tests are running (I even cleared it so I can see it filling up) but the value of start time for each result is "Invalid date"
![Screenshot 2024-02-08 at 10 45 30 AM](https://github.com/arevindh/pihole-speedtest/assets/32372166/752ce07d-9da9-4c1c-b49b-6c7e98fae72f)

**Comment by arevindh** [comment]
> after updating pihole using `pihole -up` no results are seen on the speedtest graph. in the speedtest log I can see that the tests are running (I even cleared it so I can see it filling up) but the value of start time for each result is "Invalid date" ![Screenshot 2024-02-08 at 10 45 30 AM](https://private-user-images.githubusercontent.com/32372166/303264742-752ce07d-9da9-4c1c-b49b-6c7e98fae72f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczOTEwNDcsIm5iZiI6MTcwNzM5MDc0NywicGF0aCI6Ii8zMjM3MjE2Ni8zMDMyNjQ3NDItNzUyY2UwN2QtOWRhOS00YzFjLWI0OWItNmM3ZTk4ZmFlNzJmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA4VDExMTIyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2MzBlMTBiMDhjOTc1MWZhZWU5ZGU4Mzg2ODcyNDY5ZDlhMjFlNjQyMjQxNmJhNWQwNDNmZTI3YTkwMTZhZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hkclUxW96FEaIPJnKnTGNpIgx8JJcxiAg88AA66R4wI)

Can you give more details

- Your OS 
- Browser and Version

**Comment by guygrinberger** [comment]
@arevindh 

- OS Raspbian GNU/Linux 11 (bullseye)
- Chrome 121.0.6167.85

**Comment by arevindh** [comment]
> @arevindh
> 
>     * OS Raspbian GNU/Linux 11 (bullseye)
> 
>     * Chrome 121.0.6167.85

- Are there any errors in the browser console ?
- Can you get the API Result from the speed test list page?

**Comment by guygrinberger** [comment]
@arevindh 

- no errors
- getAllSpeedTestData example
```
    "data": [
        [
            1,
            "2024-02-07 18:31:11 IST",
            "2024-02-07 18:31:26 IST",
            "Cellcom",
            "93.173.102.14",
            "Cellcom Ltd.",
            0,
            3.298,
            319.044,
            99.3512,
            "https:\/\/www.speedtest.net\/result\/c\/44a40760-0b94-4f03-94a0-b8793b72fe0d"
        ],
        [
            2,
            "2024-02-07 19:00:41 IST",
            "2024-02-07 19:00:50 IST",
            "Cellcom",
            "93.173.102.14",
            "Cellcom Ltd.",
            0,
            3.244,
            313.82,
            99.3357,
            "https:\/\/www.speedtest.net\/result\/c\/7277353f-a11e-4291-8f06-903587835078"
        ],
        [
            3,
            "2024-02-07 20:00:41 IST",
            "2024-02-07 20:00:53 IST",
            "Cellcom",
            "109.186.140.144",
            "Cellcom Ltd.",
            0,
            6.663,
            312.928,
            99.8838,
            "https:\/\/www.speedtest.net\/result\/c\/1537cd0e-1ef9-4bc0-a96c-70ea74fe4258"
        ],
        [
            4,
            "2024-02-07 21:00:41 IST",
            "2024-02-07 21:00:53 IST",
            "Cellcom",
            "109.186.140.144",
            "Cellcom Ltd.",
            0,
            6.644,
            312.775,
            99.8232,
            "https:\/\/www.speedtest.net\/result\/c\/db53c9d3-a141-4f86-810a-071a4f59418d"
        ],

```

**Comment by ipitio** [comment]
Try updating with the mod script

    curl -sSLN https://github.com/arevindh/pi-hole/raw/master/advanced/Scripts/speedtestmod/mod.sh | sudo bash -s up

**Comment by guygrinberger** [comment]
@ipitio 
still having invalid date after update

**Comment by ipitio** [comment]
#157 fixes all datetime issues (I hope)

**Comment by guygrinberger** [comment]
@ipitio 
just noticed this error while using the update script
```
fatal: HEAD does not point to a branch

  Error: Remote revision could not be obtained, please contact Pi-hole Support
```

**Comment by ipitio** [comment]
Yeah that's also fixed in the PR

**Comment by ChrisWNY** [comment]
I just updated Pi-hole to grab the latest FTL version and had to update Speedtest as well. I'm getting nothing for bar charts after pulling the latest speedtest repo. Speedtest log looks fine, If I go into Speedtest settings to "show chart preview," just see spinning arrows.

**Comment by ipitio** [comment]
Hmm are there any warnings or errors in the console?

**Comment by guygrinberger** [comment]
issue got resolved for me as well without any changes.
