### ISSUE TITLE
Speedtest Schedule: cannot change settings

### ISSUE THREAD

**Issue by gwala** [arevindh/pihole-speedtest#16]
I configured the scheduling to every hour (Settings->Speedtest->Speedtest Schedule).
Now I cannot revert it back to every 6 hours.
When I set the new value and apply, the old value (1 hour) remain.
I have tried to update PiHole, and also have reconfigured ("pihole -r") but problem still persist.

**Comment by arevindh** [comment]
Try this
```
cd /opt/pihole/
mv webpage.sh webpage.sh.org
wget https://github.com/arevindh/pi-hole/raw/master/advanced/Scripts/webpage.sh
```
If its still not working give the o/p of the command below
`cd /var/www/html/admin`
`git remote -v`

**Comment by arevindh** [comment]
Closing due to no response
