### ISSUE TITLE
[Feature Request] Show version mod in Speedtest tag

### ISSUE THREAD

**Issue by corasaniti** [arevindh/pihole-speedtest#165]
It would be nice to see the currently installed version of the mods inside the speedtest tab.
This way when you install the latest version the version should change
Thank you

Note:
I congratulate you for the excellent work. I noticed that from version 2.2 onwards the mod has become very fast, efficient and userful.

**Comment by ipitio** [comment]
Yeah I know, almost have it working. There's a dir I didn't know about; I'll fix it later today.

**Comment by town3r** [comment]
I did just notice that w/ the `Star Trek Picard LCARS theme (dark)` theme

The Speedtest settings tab is missing its title/label.

The space next to Teleporter can still be clicked to take you there, but the "Speedtest" label is missing.

![image](https://github.com/arevindh/pihole-speedtest/assets/12396203/89bfc5d1-9b8e-4cb5-8a52-66887fbb3698)

**Comment by ipitio** [comment]
That has to do with the dir I didn't know about.

**Comment by ipitio** [comment]
The label is there, that's a theme issue. I don't want to mess with the themes (since I haven't had to touch them so far), so I'd recommend using a different theme if you want to see the label.

**Comment by arevindh** [comment]
> The label is there, just hidden on the right, that's a theme issue. I don't want to mess with the themes (since I haven't had to touch them so far), so I'd recommend using a different theme if you want to see the label.

Let me try today

**Comment by corasaniti** [comment]
@arevindh 
installed v2.4.2 version but broken link still in footer
https://github.com/arevindh/pihole-speedtest/releases/vDev
Thanks

**Comment by corasaniti** [comment]
@ipitio @arevindh 
sorry it was a browser cache problem...
I'm closing the issue
Thank you
![Cattura](https://github.com/arevindh/pihole-speedtest/assets/5001932/50fdec6c-14a3-4f26-8517-957dc94328ad)

**Comment by corasaniti** [comment]
@ipitio 
works fine but now the link points to 2.4.2 and not the latest 2.4.3. You did not push the version forward to the latest release 2.4.3

**Comment by ipitio** [comment]
It should be the latest version... try refreshing the page.

**Comment by corasaniti** [comment]
> It should be the latest version... try refreshing the page.
again a browser cache problem
Thank you
![Cattura](https://github.com/arevindh/pihole-speedtest/assets/5001932/15de4904-1a47-46b8-a5b4-9fba78597d4b)
