### ISSUE TITLE
Speedtest option still on dashboard even though already removed

### ISSUE THREAD

**Issue by SonThanhVN** [arevindh/pihole-speedtest#167]
After removing Speedtest mod, the option for speedtest mod on the web dashboard still appear
![image](https://github.com/arevindh/pihole-speedtest/assets/46934330/6799b8c6-d875-42db-91d5-90ba0e508eb4)

**Comment by ipitio** [comment]
Try reinstalling latest, uninstalling again, and clearing browser cache.

**Comment by SonThanhVN** [comment]
i have tried but not working

**Comment by ipitio** [comment]
Did you uninstall via the button or by running the script directly in the terminal?

**Comment by SonThanhVN** [comment]
i have tried both way

**Comment by ipitio** [comment]
You can use the command from my repo to uninstall for now:

    curl -sSLN https://github.com/ipitio/pihole-speedtest/raw/ipitio/mod.sh | sudo bash -s un

I'm not yet sure why the one on the master branch isn't working.

**Comment by SonThanhVN** [comment]
thanks
this command worked

**Comment by ipitio** [comment]
This is now fixed in arevindh/pi-hole#83
