### ISSUE TITLE
Integration to original project

### ISSUE THREAD

**Issue by abacao** [arevindh/pihole-speedtest#18]
Hi there,

Have you tried to open a feature PR in the original project adding this mod to the original project?
It would be great if pihole accepted this in their code.  The installation would become easier to more people and the updates for pihole would be easier for everyone who had the mod.

**Comment by arevindh** [comment]
Here the reply from them [Link](https://discourse.pi-hole.net/t/simple-speedtest-added-to-pihole-web-ui-takes-tests-every-hour/4053/7?u=itsmesid)
