### ISSUE TITLE
Result over last 24 hours instead over last 1 days

### ISSUE THREAD

**Issue by antiabed** [arevindh/pihole-speedtest#2]
This is very minor, but other stats in the Pi-hole interface say "Queries over last 24 hours", it would match better if the Speedtest stat used the phrasing "Speedtest results over last 24 hours: instead of "Speedtest results over last 1 Days".

**Comment by arevindh** [comment]
@antiabed Speedtest mod supports multiple durations to show on the main dashboard, that's the reason why its shows `{duration}` days. Anyway, it won't matter anymore since pihole is getting rid of the current UI for a cleaner UI using ReactJS.

**Comment by antiabed** [comment]
Ah, I didn't know that. Does that mean the speedtest won't be available anymore?

**Comment by arevindh** [comment]
I'm along working with Pihole team to make it available on the next version too.

**Comment by Illustratum** [comment]
Love this btw!
