### ISSUE TITLE
Raspberry Pi 4 Raspbian Buster Lite

### ISSUE THREAD

**Issue by cronus130** [arevindh/pihole-speedtest#20]
Speedtest installs and runs normally via command line manually, however it doesn’t run automatically when scheduled in the GUI.

**Comment by arevindh** [comment]
Is it a fresh install or an upgrade?

**Comment by cronus130** [comment]
Fresh install, including all latest updates/patches.

**Comment by arevindh** [comment]
Can you retry the [update](https://github.com/arevindh/pihole-speedtest/wiki/Updating--Speedtest-Mod) script, set the test period to 1 hour in the settings page then check after few hours.

**Comment by cronus130** [comment]
I've run the update script as well as a complete uninstall and reinstall, same problem. I have it set to 1 hour with a 7 day range.

**Comment by arevindh** [comment]
The issues seem to come from crontab. Let me try to fix it.

**Comment by arevindh** [comment]
@cronus130 Can you run the update [script ](https://github.com/arevindh/pihole-speedtest/wiki/Updating--Speedtest-Mod)and try once more.

**Comment by cronus130** [comment]
Looks like that did it, just completed the first speedtest automatically.
