### ISSUE TITLE
After Restart Pihole docker container dont start

### ISSUE THREAD

**Issue by elisa9180** [arevindh/pihole-speedtest#21]
[s6-finish] syncing disks.

[s6-finish] sending all processes the TERM signal.

[s6-finish] sending all processes the KILL signal and exiting.

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.

[s6-init] ensuring user provided files have correct perms...exited 0.

[fix-attrs.d] applying ownership & permissions fixes...

[fix-attrs.d] 01-resolver-resolv: applying... 

[fix-attrs.d] 01-resolver-resolv: exited 0.

[fix-attrs.d] done.

[cont-init.d] executing container initialization scripts...

[cont-init.d] 20-start.sh: executing... 

/root/ph_install.sh: line 48: setupVars: readonly variable

[cont-init.d] 20-start.sh: exited 1.

[cont-finish.d] executing container finish scripts...

[cont-finish.d] done.

[s6-finish] syncing disks.

[s6-finish] sending all processes the TERM signal.

[s6-finish] sending all processes the KILL signal and exiting.

**Comment by arevindh** [comment]
Can you give relevant files to test from my side?

**Comment by elisa9180** [comment]
I can give you the docker compose install the speed test in the container and reboot you will see the container don't start pihole any more.

Change the serverIP in your IP RANGE and also your HOME detections

sudo docker run -d --name "pihole" -p 53:53/tcp -p 53:53/udp -p 67:67/udp -p 8080:80 -p 4443:443 --dns 127.0.0.1 --dns 1.1.1.1 --cap-add=NET_ADMIN -v "/home/docker/pihole/piholednsmasq.d/:/etc/piholednsmasq.d/" -v /etc/localtime:/etc/localtime:ro -v "/home/docker/pihole/pihole/:/etc/pihole/" -v "/home/docker/pihole/pihole-script/:/etc/pihole-script/" -v "/home/docker/pihole/dnsmasq.d/:/etc/dnsmasq.d/" -e ServerIP="10.0.30.27" --restart=always pihole/pihole:latest

**Comment by arevindh** [comment]
If you can give docker-compose, will try it from end.

**Comment by elisa9180** [comment]
docker run -d --name "pihole" -p 53:53/tcp -p 53:53/udp -p 67:67/udp -p 8080:80 -p 4443:443 --dns 127.0.0.1 --dns 1.1.1.1 --cap-add=NET_ADMIN -v "/home/docker/pihole/piholednsmasq.d/:/etc/piholednsmasq.d/" -v /etc/localtime:/etc/localtime:ro -v "/home/docker/pihole/pihole/:/etc/pihole/" -v "/home/docker/pihole/pihole-script/:/etc/pihole-script/" -v "/home/docker/pihole/dnsmasq.d/:/etc/dnsmasq.d/" -e ServerIP="10.0.30.27" --restart=always pihole/pihole:latest
