### ISSUE TITLE
Speedtest upload capped

### ISSUE THREAD

**Issue by paralovosca** [arevindh/pihole-speedtest#23]
Love the mod!

Only issue I seem to have is upload appears to show as capped at ~2.8 Mbits with very little deviation.  Download looks good and will show appropriate deviations.

**Comment by arevindh** [comment]
It won't cap your upload, check your firewall.

**Comment by paralovosca** [comment]
I installed speedtest-cli via homebrew on a couple of my other devices (mac) and I noticed I was getting what I should for upload speed.  I am wondering if my raspberry pi 4 is the limitation....not sure how to further investigate my raspberry pi?

**Comment by arevindh** [comment]
If you have UI try running speedtest from browser.

**Comment by paralovosca** [comment]
I vnc'd into pihole and ran ookla speedtest from a browser and received 9.13 mbps.  So I think raspberry pi is no the limitation and my firewall shouldn't be a problem since i can run speedtest-cli on other devices off same switch and subnet.

**Comment by paralovosca** [comment]
I played around with a few switches for speedtest-cli.  Apparently the speedtest servers closest to me are the problem.  I ran a server list and grabbed a few servers further away then the closest three and they all report appropriate upload speeds.  Weird.  Now I think I remember that I can select a custom server in the gui....

**Comment by paralovosca** [comment]
Speedtest-cli is not the issue.  Certain speedtest servers are the issue. Changing to a custom server fixed my original issue of what appeared to be a capped upload speed.

**Comment by arevindh** [comment]
Use the test server id in settings page on pihole.
