### ISSUE TITLE
Pi-hole update admin-LTE to 4.3.2

### ISSUE THREAD

**Issue by Natizyskunk** [arevindh/pihole-speedtest#26]
Please can you update your pi-hole admin repo with the last 4.3.2 official update please ? 🙂

# reference: https://github.com/arevindh/AdminLTE/issues/19

**Comment by arevindh** [comment]
Sure, Thanks for the update. 
Will do it today itself.

**Comment by arevindh** [comment]
Updated

**Comment by Natizyskunk** [comment]
Thanks a lot !
