### ISSUE TITLE
request - dump speedtest to csv locally or with gSYNC

### ISSUE THREAD

**Issue by nosaturn** [arevindh/pihole-speedtest#27]
i have a script running speedtest and parsing it to a local .csv which is synced to my Google Drive. it would be nice to eliminate this redundancy. Could the speedtest.db file be dumped to .csv or something or even have the pi-hole interface let me specify a link to regularly export the file to?

**Comment by arevindh** [comment]
Let me try.

**Comment by jolleyutah** [comment]
Even if not schedule able, it would be nice to have an "export to CSV" button on the speedtest results interface.
