### ISSUE TITLE
Speedtest on pihole representative?

### ISSUE THREAD

**Issue by sanderboom** [arevindh/pihole-speedtest#29]
First of all: thanks for this piece of software.

More of a general issue, whether the results of speedtest on PiHole actually representative are for the speeds on the rest of the network.

On my laptop (connected wireless 5Ghz):
```
Hosted by ...[3.08 km]: 15.687 ms
Download: 198.61 Mbit/s
Upload: 24.92 Mbit/s
```

PiHole speedtest  (connected by CAT5 cable):
```
Hosted ... [2.69 km]: 24.043 ms
Download: 18.24 Mbit/s
Upload: 21.51 Mbit/s
```

Could this be because of the low specs of the RPi (version 1)? In this way, the PiHole speedtest is not really representative. Do I overlook something in my setup? 

TIA.

**Comment by arevindh** [comment]
Most probably. 
Try downloading a file with wget or curl to confirm the speed.

**Comment by sanderboom** [comment]
Speeds seem more or less the same using `wget`, but I'll get an newer version pi soon anyway and migrate.
