### ISSUE TITLE
Request: more flexible graph fx on db_graph.php page

### ISSUE THREAD

**Issue by roerigdalgaard** [arevindh/pihole-speedtest#30]
Hi 
It would be great to run som more flexible reports on the speedtest stats. 
fx following the rules on the db_graph.php page...

This would be a great stats reporting :-)

**Comment by arevindh** [comment]
I didn't get you, can you explain a little more.

**Comment by roerigdalgaard** [comment]
I can try :-)

By default you can only see the grafical presentation of the measurments on the admin startpage based og the general defined rules.

PiHole has the posibilyt at show grafics of longterm data. (/admin/db_graph.php)

It would be great if this page could show the speedtest graphs too (based on the choosen timeframes from the date/time pickers)

More clear?

**Comment by trossr32** [comment]
Here's my upvote for this. It would be great to be able to set a start and end date for data shown in the graph on the dashboard, or on a graph in a separate tab.
