### ISSUE TITLE
ISSUE: Upload speed is not accurate

### ISSUE THREAD

**Issue by dwilasnd** [arevindh/pihole-speedtest#31]
I installed the code today.
Two speedtests initiated from the commandline.
http://www.speedtest.net/result/8704190754.png
https://www.speedtest.net/result/8704105248.png

Result from a webpage request
https://www.speedtest.net/result/8704129316

It looks like the upload is a couple of decimals off.

**Comment by arevindh** [comment]
Try this command `speedtest-cli`

**Comment by dwilasnd** [comment]
speedtest-cli
Retrieving speedtest.net configuration...
Testing from Verizon Business (205.197.219.150)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by Direct Communications - Cedar Valley (Eagle Mountain, UT) [16.12 km]: 8.028 ms
Testing download speed................................................................................
Download: 413.97 Mbit/s
Testing upload speed......................................................................................................
Upload: 4.13 Mbit/s

**Comment by dwilasnd** [comment]
sudo pihole -a -sn

Testing Speed
2019-10-25 12:51:33 2019-10-25 12:51:57 Verizon Business 205.197.219.150 Brigham Young University (Provo, UT) 23.02 355.827 321.11 4.13 http://www.speedtest.net/result/8704844467.png

**Comment by arevindh** [comment]
Try manually setting the server from the list 
https://c.speedtest.net/speedtest-servers-static.php

**Comment by dwilasnd** [comment]
The server is manually set to 4793 which is the 2nd speed test (pihole -a -sn). The first test didnt seem to pick that up.

**Comment by dwilasnd** [comment]
speedtest-cli --server 4793
Retrieving speedtest.net configuration...
Testing from Verizon Business (205.197.219.150)...
Retrieving speedtest.net server list...
Retrieving information for the selected server...
Hosted by Brigham Young University (Provo, UT) [23.02 km]: 17.35 ms
Testing download speed................................................................................
Download: 338.20 Mbit/s
Testing upload speed......................................................................................................
Upload: 4.14 Mbit/s

**Comment by arevindh** [comment]
try selecting another one

**Comment by dwilasnd** [comment]
` speedtest-cli --server 2065
Retrieving speedtest.net configuration...
Testing from Verizon Business (205.197.219.150)...
Retrieving speedtest.net server list...
Retrieving information for the selected server...
Hosted by Utah Education Network (Salt Lake City, UT) [39.67 km]: 34.543 ms
Testing download speed................................................................................
Download: 302.63 Mbit/s
Testing upload speed......................................................................................................
Upload: 4.10 Mbit/s
`

**Comment by dwilasnd** [comment]
```
speedtest-cli --server 4272
Retrieving speedtest.net configuration...
Testing from Verizon Business (205.197.219.150)...
Retrieving speedtest.net server list...
Retrieving information for the selected server...
Hosted by Vivint Wireless (Salt Lake City, UT) [39.67 km]: 55.851 ms
Testing download speed................................................................................
Download: 196.93 Mbit/s
Testing upload speed......................................................................................................
Upload: 3.84 Mbit/s
```

**Comment by dwilasnd** [comment]
```
speedtest-cli --server 1781
Retrieving speedtest.net configuration...
Testing from Verizon Business (205.197.219.150)...
Retrieving speedtest.net server list...
Retrieving information for the selected server...
Hosted by Comcast (Salt Lake City, UT) [39.67 km]: 43.183 ms
Testing download speed................................................................................
Download: 195.09 Mbit/s
Testing upload speed......................................................................................................
Upload: 4.10 Mbit/s

```

**Comment by arevindh** [comment]
Seems there is some issue with your device or firewall.

**Comment by dwilasnd** [comment]
From the actual webpage, it's 300+MBs

https://www.speedtest.net/result/8704563190

**Comment by arevindh** [comment]
Are you running it on a pi?

**Comment by karimnouh** [comment]
@dwilasnd Try testing with and without upload preallocation `--no-pre-allocate` . Also use server 12450 (The same server you used with the webpage test).

`speedtest-cli --server 12450 --no-pre-allocate`
`speedtest-cli --server 12450`

**Comment by dwilasnd** [comment]
It's AWLAYS 4Mbit...

```
speedtest-cli --server 12450 --no-pre-allocate
Retrieving speedtest.net configuration...
Testing from Manti Telephone (205.197.219.150)...
Retrieving speedtest.net server list...
Retrieving information for the selected server...
Hosted by CentraCom (Fairview, UT) [92.20 km]: 4.474 ms
Testing download speed................................................................................
Download: 273.21 Mbit/s
Testing upload speed......................................................................................................
Upload: 4.06 Mbit/s
```

**Comment by dwilasnd** [comment]
> Are you running it on a pi?

Ubuntu VM

**Comment by arevindh** [comment]
Please post your question on the  `speedtest-cli` Github repo
https://github.com/sivel/speedtest-cli

**Comment by rross101** [comment]
Just for completeness; I had this issue, it's because the version of speediest-cli installed by standard raspbian is broken; if you install the newest version from the link above it solves the problem. I thought it was worth posting this here as it took me forever to discern what the problem was.
