### ISSUE TITLE
will this work in pi-hole 5.0?

### ISSUE THREAD

**Issue by flipptx** [arevindh/pihole-speedtest#34]
wandering if this will work with the new 5.0

**Comment by arevindh** [comment]
Will integrate speed-test once they release it.

**Comment by flipptx** [comment]
thanks, just wasn't sure if it was working with the beta version yet.

**Comment by arevindh** [comment]
@flipptx Updated to v5.0

**Comment by Poisoned** [comment]
@arevindh I don't see any code changes, only that you changed the changelog. Say everything works out of the box with Pi-hole v5.0?

**Comment by arevindh** [comment]
@Poisoned This is not the real repo with codes. Check here : https://github.com/arevindh/AdminLTE
