### ISSUE TITLE
lighttpd error log

### ISSUE THREAD

**Issue by BigBobDalton** [arevindh/pihole-speedtest#35]
The GUI throws an error at  $data = getSpeedTestData($dbSpeedtest,-1);
      if($data['errr'])

indicating that errr is not defined as an index

ideas?

**Comment by arevindh** [comment]
Is it a warning or error?
Can u post the specific part of log.

**Comment by BigBobDalton** [comment]
It shows up in my error.log file in directory /var/log/lighttpd/ every time I change view from graph to list

2020-04-29 21:51:45: (mod_fastcgi.c.2543) FastCGI-stderr: PHP Notice:  Undefined index: errr in /var/www/html/assets/php/data.php on line 124

**Comment by BigBobDalton** [comment]
Removing the script 
$data = getSpeedTestData($dbSpeedtest,-1);
      if($data['errr'])
        return [];
seems to correct the error being thrown, although I am uncertain if it causes some sort of different issue.  It doesn't seem to bother anything by removing it

**Comment by arevindh** [comment]
Its just a notice don't worry . Since they have made massive changes on code for next version . Will fix it in next version along with the new changes.

Thanks for the donation .

**Comment by arevindh** [comment]
@BigBobDalton Updated to version 5.0 , can you test and confirm whether the message is still there?

**Comment by BigBobDalton** [comment]
Sorry, I’ve discontinued usage of pihole with version 5 and am using AdGuardHome instead.  Apologies.

 

 

Von: itsmesid <notifications@github.com>
Antworten an: arevindh/pihole-speedtest <reply@reply.github.com>
Datum: Montag, 11. Mai 2020 um 19:57
An: arevindh/pihole-speedtest <pihole-speedtest@noreply.github.com>
Cc: BigBobDalton <bob@dalton.li>, Mention <mention@noreply.github.com>
Betreff: Re: [arevindh/pihole-speedtest] lighttpd error log (#35)

 

@BigBobDalton Updated to version 5.0 , can you test and confirm whether the message is still there?
