### ISSUE TITLE
AdminLTE 5.0

### ISSUE THREAD

**Issue by mgarland1988** [arevindh/pihole-speedtest#36]
What is the process of upgrading from 4.x to 5.0 adminLTE? PiHole -up does not upgrade adminLTE. Would the steps be:
Uninstall speed test mod, upgrade adminLTE, then install speed test mod again?
Thanks

**Comment by flipptx** [comment]
did you have any luck? I'm sat at the same right now.

**Comment by josh3003** [comment]
Yep you need to run the below commands it updated my web interface.

sudo rm /var/www/html/admin
sudo git clone https://github.com/pi-hole/AdminLTE.git /var/www/html/admin
pihole -r and select repair

I can't get the speedtest working at the moment I think it needs to be updated.

**Comment by arevindh** [comment]
@flipptx @mgarland1988 @josh3003  : Updated to v5.0 . 
I you don't mind, can you update and test it ?

**Comment by flipptx** [comment]
> @flipptx @mgarland1988 @josh3003 : Updated to v5.0 .
> I you don't mind, can you update and test it ?

bash: line 2: whiptail: command not found
bash: line 4: whiptail: command not found

**Comment by flipptx** [comment]
i don't see the speediest mod after the update just regular pi-hole screen, and the screen now shows this... "Pi-hole Version v5.0 Web Interface Version v4.3.3 (Update available!) FTL Version v5.0" any thoughts? do i need to reinstall the MOD vs just update?

**Comment by ChrisWNY** [comment]
I used the update command and PiHole is still reading v4.3.3 for the Web Interface version. From the CLI, this is how it's reported (when using the speedtest AdminLTE):

  Pi-hole version is v5.0 (Latest: v5.0)
  AdminLTE version is v4.3.3-508-g25a0f385 (Latest: v5.0)
  FTL version is v5.0 (Latest: v5.0)

The UI does look like version 5.0 and the left-hand menu is now correct (the once-and-done update script however still isn't working properly, reverts PiHole's web UI to 4.3.3. Speedtest functionality is working and the speedtest data shows up fine, but the version is still out of whack.

**Comment by josh3003** [comment]
@arevindh 
Hey, I ran the steps again and I have the speedtest mod working on AdminLTE 5.0 

Thanks for pushing an update so quickly.

**Comment by flipptx** [comment]
so i may be little different i didn't have it working on 4.3, i installed v5 and followed the install steps and updated. doesn't seem to have added anything to pi-hole any thought if this could be the problem and if so how to get it up?

**Comment by josh3003** [comment]
Oh yeah it does show web interface is 4.3.3 that's probably just cosmetic as it does show it is up to date in commandline. Probably just another quick update to fix it

**Comment by arevindh** [comment]
Try `pihole updatechecker local` , it might fix the issue

**Comment by arevindh** [comment]
@josh3003 : Will try once my office time is over.

**Comment by mgarland1988** [comment]
> @josh3003 : Which one will you prefer ?
> ![stacked](https://user-images.githubusercontent.com/693151/81646142-5a31f100-9448-11ea-9318-ffdfb4b56648.png)
> ![normal](https://user-images.githubusercontent.com/693151/81646166-628a2c00-9448-11ea-84db-10ec84853771.png)

@arevindh This looks brilliant! :) 
Thank you everyone with your help and support
I am yet to update, so I can test from AdminLTE version 4.3.3. Please let me know what steps do you want me to carry out, and I can test the process.

Thank you all

**Comment by arevindh** [comment]
@mgarland1988  : I think second one is better , what do you think  ?

**You can use manual instructions ** 
https://github.com/arevindh/pihole-speedtest/wiki/Updating--Speedtest-Mod#manual-instructions

**Comment by mgarland1988** [comment]
> @mgarland1988 : I think second one is better , what do you think ?
> 
> You can use manual instructions
> 
> https://github.com/arevindh/pihole-speedtest/wiki/Updating--Speedtest-Mod#manual-instructions

@arevindh Thank you so much for all your support - this works perfectly :)

I will close this case - really appreciate all your hard work

I agree, the second graphic is better! 👍

**Comment by arevindh** [comment]
Please pull `admin` once more i have updated line chart to bar chart
