### ISSUE TITLE
 pi-hole Web UI still showing 4.3.3 instead of 5.0

### ISSUE THREAD

**Issue by ChrisWNY** [arevindh/pihole-speedtest#37]
Version info is out-of-whack in pi-hole after updating pi-hole to 5.0, then running the speedtest mod update post 5.0 update. 

I did the following after updating pi-hole to 5.0 to incorporate the speedtest mod back into pi-hole 5.0:

---------------------------------------------

cd /var/www/html/
mv admin org_admin # remove old org_admin folder if exists
git clone https://github.com/arevindh/AdminLTE admin

Get latest webpage.sh file

cd /opt/pihole/
mv webpage.sh webpage.sh.org # remove old webpage.sh.org file if exists
wget https://github.com/arevindh/pi-hole/raw/master/advanced/Scripts/webpage.sh
chmod +x webpage.sh

Update version info

pihole updatechecker local

----------------------------------------------

After "updating" the speedtest mod, within the CLI, running "pihole -v" returns the following:

  Pi-hole version is v5.0 (Latest: v5.0)
  AdminLTE version is v4.3.3-508-g25a0f385 (Latest: v5.0)
  FTL version is v5.0 (Latest: v5.0)

The Web UI does look like 5.0 instead of 4.3 (left-hand menu is correct and has the new Local DNS and other links as pi-hole 5.0 should have), but the version is still reporting 4.3.3.

**Comment by arevindh** [comment]
Try this 

> sudo su
> cd /var/www/html/admin
> git pull
> pihole updatechecker local
> exit

**Comment by ChrisWNY** [comment]
That took care of the version discrepancy. Thanks! Issue resolved.

**Comment by PJGitHub9** [comment]
Im having the same issue, i cant seem to update. I ran that command and it didnt work :(

**Comment by flipptx** [comment]
sudo su
cd /var/www/html/admin
git pull
pihole updatechecker local
exit  

fixed it thanks
