### ISSUE TITLE
Speedtest results inaccurate

### ISSUE THREAD

**Issue by georgeoommen** [arevindh/pihole-speedtest#38]
Followed the instructions to install and update the Speedtest mod for pi-hole, however the results I'm getting are very very inaccurate.

**Comment by arevindh** [comment]
Try running `speedtest-cli` from console .

**Comment by flipptx** [comment]
why are they so inaccurate? (don't forget the limits of the R-Pi Lan)

**Comment by arevindh** [comment]
This Project is based on speedtest-cli. The text below is from their repository [readme](https://github.com/sivel/speedtest-cli#inconsistency) file.

> It is not a goal of this application to be a reliable latency reporting tool.

> Latency reported by this tool should not be relied on as a value indicative of ICMP
> style latency. It is a relative value used for determining the lowest latency server
> for performing the actual speed test against.

> There is the potential for this tool to report results inconsistent with Speedtest.net.
> There are several concepts to be aware of that factor into the potential inconsistency:

> 1. Speedtest.net has migrated to using pure socket tests instead of HTTP based tests
> 2. This application is written in Python
> 3. Different versions of Python will execute certain parts of the code faster than others
> 4. CPU and Memory capacity and speed will play a large part in inconsistency between
   Speedtest.net and even other machines on the same network

> Issues relating to inconsistencies will be closed as wontfix and without
> additional reason or context.

**Comment by georgeoommen** [comment]
> why are they so inaccurate? (don't forget the limits of the R-Pi Lan)

Am running it on R-Pi. It’s lan limitation must be the issue. Will test on another machine and report back of issue continues.

**Comment by arevindh** [comment]
Please refer https://github.com/sivel/speedtest-cli
