### ISSUE TITLE
Retry failed aborting

### ISSUE THREAD

**Issue by P8Kcv6n** [arevindh/pihole-speedtest#39]
This is on a Google Cloud Compute Engine VM on Ubuntu 18.04.4 LTS. The issue occurred when I had pihole v4 and still occurs after upgrading to v5.

`speedtest-cli` runs fine, returning:
```
Retrieving speedtest.net configuration...
Testing from Google Cloud...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by Cox - Nova (Fairfax, VA) [21.49 km]: 13.976 ms
Testing download speed................................................................................
Download: 1192.34 Mbit/s
Testing upload speed................................................................................................
Upload: 542.49 Mbit/s
```
`sudo pihole -a -sn` however, returns this:
```

Testing Speed
/var/www/html/admin/scripts/pi-hole/speedtest/speedtest.sh: line 320:  4517 Killed                  $cmd > $log
/var/www/html/admin/scripts/pi-hole/speedtest/speedtest.sh: line 320:  4675 Killed                  $cmd > $log
Connection Failed Retry after 30 sec Connection Failed Retry failed aborting
```

The log shows this:
```
Retrieving speedtest.net configuration...
Testing from Google Cloud...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by Xiber LLC (Washington, DC) [31.89 km]: 13.271 ms
Testing download speed................................................................................
Download: 1244.80 Mbit/s
Testing upload speed........................................................................
```

**Comment by arevindh** [comment]
Can you update speedtest mod and retry?

**Comment by P8Kcv6n** [comment]
Updated. Now `speedtest` runs fine, but `sudo pihole -a -sn` still terminates on the same line.

**Comment by arevindh** [comment]
`sudo pihole -a -sn` uses old method (Python). Will fix it in next release.

**Comment by P8Kcv6n** [comment]
I don't see the drop down menu.

[image](https://user-images.githubusercontent.com/21136719/83851444-5e1c0080-a6e0-11ea-9e57-4a8918b10468.png)

**Comment by arevindh** [comment]
@P8Kcv6n . follow these [Instruction](https://github.com/arevindh/pihole-speedtest/wiki/Updating--Speedtest-Mod) .

**Comment by P8Kcv6n** [comment]
Yeah I installed speedtest-cli and tried the one-click update, didn't work. Also tried manually updating, reinstalling the mod, and rebooting.

**Comment by arevindh** [comment]
Tried clear cache on browser ? 
Hope you have install Speedtest CLI  https://www.speedtest.net/apps/cli

**Comment by P8Kcv6n** [comment]
Yes, that's the Speedtest CLI that I installed. I've tried deleting the website data for pi.hole in Chrome and Safari. 

The output of that command is:
```
                                </div>
                            </form>
                        </div>
                    </div>
                </div>



```

**Comment by arevindh** [comment]
Seems codebase is not updated. Please run and post output
`sudo su`
`cd /var/www/html/admin`
`git remote -v`
`git status`
`git pull`

**Comment by P8Kcv6n** [comment]
As I mentioned in the edit in my last comment, the file updated on my last attempt. 

But now I've noticed that the speed test runs hourly even when disabled. Should I post a separate issue? I tried selecting the python method to stop it, but it seems to work now too!

**Comment by arevindh** [comment]
@P8Kcv6n Seems I missed that one when implementing official speedtest. Fixed now . 
```
sudo su
cd /opt/pihole/
rm webpage.sh
wget https://github.com/arevindh/pi-hole/raw/master/advanced/Scripts/webpage.sh
chmod +x webpage.sh
```

**Comment by P8Kcv6n** [comment]
That didn't stop them, tried both disabling in the web ui and in the shell with `pihole -a -s 0`

**Comment by arevindh** [comment]
> @P8Kcv6n Seems I missed that one when implementing official speedtest. Fixed now .
> 
> ```
> sudo su
> cd /opt/pihole/
> rm webpage.sh
> wget https://github.com/arevindh/pi-hole/raw/master/advanced/Scripts/webpage.sh
> chmod +x webpage.sh
> ```

@P8Kcv6n can you try same steps now ?

**Comment by P8Kcv6n** [comment]
Sorry for the late reply, but that worked--it disables now. Everything seems to be working well, including with my local pihole machine.
