### ISSUE TITLE
Graphs issues from Left side to Right side.

### ISSUE THREAD

**Issue by gordon15969** [arevindh/pihole-speedtest#4]
The graph numbering is correct on the left side for speed, but as you go to the right side everything is multiplied by 10.  Please correct the right side of the speedtest results graph.

![screen shot 2018-09-28 at 7 11 36 am](https://user-images.githubusercontent.com/43672843/46205454-a28db100-c2ee-11e8-8142-5659403f6b37.png)

**Comment by ctp-mandreasen** [comment]
Pretty sure you got 
- bandwidth on the left side (blue/red)
- latency on the right side (green)
And judging from your graph the speedtestserver is pretty far from you.

That's the way mine works anyway.

**Comment by arevindh** [comment]
@ctp-mandreasen I agree with @ctp-mandreasen.
