### ISSUE TITLE
Speedtest showing much slower speed than actual one

### ISSUE THREAD

**Issue by PJGitHub9** [arevindh/pihole-speedtest#41]
My pihole is showing downloads of ~ 30mbps-70mbps. My download is 100mbps, even when i run the speedtest via my pc it shows 90+mbps. Any ideas? 

(Pi is connected via ethernet and is running dietpi)

**Comment by arevindh** [comment]
Which testing mode are you using?
Try updating and changing testing mode to official speedtest cli.
https://github.com/arevindh/pihole-speedtest/wiki/Updating--Speedtest-Mod

**Comment by PJGitHub9** [comment]
so I followed this tutorial
https://pimylifeup.com/raspberry-pi-internet-speed-monitor/

then i used your one line update command to update the speedtest, its still running very slow.

**Comment by arevindh** [comment]
Install this https://www.speedtest.net/apps/cli
then 
https://github.com/arevindh/pihole-speedtest/wiki/Updating--Speedtest-Mod
then go to settings speedtest and change Test Mode to `official speedtest cli`

**Comment by PJGitHub9** [comment]
Where do i find that setting? its not in the pihole interface

**Comment by PJGitHub9** [comment]
where do i find the setting for the test mode?
