### ISSUE TITLE
Both official client and python client show slow speeds

### ISSUE THREAD

**Issue by PJGitHub9** [arevindh/pihole-speedtest#42]
For some reason i cant get proper speeds on my pihole. Ive tried restarting, changing from official to python and the speeds have been consistently very slow (I have 100mbps download). Not sure why they are like this. 

[Picture](https://i.imgur.com/hsqxt1B.png)

**Comment by arevindh** [comment]
Which device are you running it on?

**Comment by PJGitHub9** [comment]
Raspberry Pi 3B, running dietpi

**Comment by arevindh** [comment]
Try running a simple download via wget or curl and check the speeds.

**Comment by PJGitHub9** [comment]
Im not too sure how to do that at all sorry, any commands I can copy via ssh?

**Comment by arevindh** [comment]
Which location is nearby you ?

![image](https://user-images.githubusercontent.com/693151/84971025-760c6f00-b139-11ea-8ff8-722e5f7c8c26.png)

**Comment by PJGitHub9** [comment]
TOR1, I ran the code: 
wget -O /dev/null http://speedtest-tor1.digitalocean.com/100mb.test

Speed is showing 500-800KB/s

**Comment by arevindh** [comment]
Download the same file using PC or MAC

**Comment by PJGitHub9** [comment]
My desktop shows 80-90Mbps

**Comment by arevindh** [comment]
If `wget` is showing lower speeds it might be due to some configurations on firewall .

**Comment by PJGitHub9** [comment]
The pi's firewall? Dietpi doesnt come preinstalled with any, im not sure what settings to check on the pi either

**Comment by arevindh** [comment]
No, do you have one on your network ?

**Comment by PJGitHub9** [comment]
No, i have another pi running the exact same setup (just no speedtest) and that one runs the Wget command at 8MB/s

**Comment by arevindh** [comment]
Is it running same diet pi ? 
**Speed test does not modify your system wget speed**

**Comment by PJGitHub9** [comment]
yeah, i uninstalled the speedtest (using your uninstall file commands) and now running the wget command bumps me up to 8MB/s (~ 64mpbs, still much slower than my actual speed)

**Comment by arevindh** [comment]
> yeah, i uninstalled the speedtest (using your uninstall file commands) and now running the wget command bumps me up to 8MB/s (~ 64mpbs, still much slower than my actual speed)

That's weird it shouldn't affect speeds.  There might be other reasons.About 8 Mb/s, Pi might have write speed limits.

**Comment by arevindh** [comment]
You might still have official speed test, try running `speedtest` from terminal.

**Comment by PJGitHub9** [comment]
54Mbit/s down and 10Mbit/s upload. Download is still like 50% of my actual, upload is exactly the right speed

**Comment by arevindh** [comment]
Which server is used for the test in pc and pi? 
I am running it on a Pi 2B+ getting upto 89 on my 125 Mbps connection.

**Comment by PJGitHub9** [comment]
Instead of going through all this struggle, i might just wipe the pi and install raspbian OS instead, it may be the OS thats causing the issue. Ill try that tomorrow and will update the post :)
