### ISSUE TITLE
Show failed speedtests as 0?

### ISSUE THREAD

**Issue by brycedjohnson** [arevindh/pihole-speedtest#43]
Might be nice to show failed speedtests as dl/up 0 in the graph?  Had an internet outage today from for 11 hrs and looked back to see when the last successful test was run to see when it started and ended and if it was was working at all in between.

Thanks for the great work!  Very useful!

**Comment by arevindh** [comment]
@brycedjohnson Let me try.

**Comment by arevindh** [comment]
@brycedjohnson : Feature is now added in the `dev` branch , wil you be able to test before it goes live ?

**Comment by brycedjohnson** [comment]
Sure thing!  Thanks!

**Comment by arevindh** [comment]
```
sudo su
cd /var/www/html/admin
git pull
git checkout dev
```
Now go to settings set an invalid speedtest id 

Test by running `sudo "/var/www/html/admin/scripts/pi-hole/speedtest/speedtest-official.sh"`

**Comment by karimnouh** [comment]
@arevindh Tested and confirmed to work. Thanks for making it happen.
![image](https://user-images.githubusercontent.com/25754437/88618059-c68eba80-d05d-11ea-986f-dcfe271db401.png)
![image](https://user-images.githubusercontent.com/25754437/88617986-921afe80-d05d-11ea-8299-93cfd569e275.png)

**Comment by brycedjohnson** [comment]
I'm getting a error when I run the script
`
root@raspberrypi:/var/www/html/admin# /var/www/html/admin/scripts/pi-hole/speedtest/speedtest-official.sh
Testing with 10051
usage: speedtest [-h] [--no-download] [--no-upload] [--bytes] [--share]
                 [--simple] [--csv] [--csv-delimiter CSV_DELIMITER]
                 [--csv-header] [--json] [--list] [--server SERVER]
                 [--exclude EXCLUDE] [--mini MINI] [--source SOURCE]
                 [--timeout TIMEOUT] [--secure] [--no-pre-allocate]
                 [--version]
speedtest: error: unrecognized arguments: -s 10051 --accept-gdpr --accept-license -f json-pretty
2020-07-28 09:38:09     2020-07-28 09:38:10                             0
Error: near ",": syntax error
`
I'm on 5.1?  Maybe there is an issue there?

**Comment by arevindh** [comment]
@brycedjohnson can you update and try 

https://github.com/arevindh/pihole-speedtest/wiki/Updating--Speedtest-Mod

**Comment by karimnouh** [comment]
@brycedjohnson You probably currently have [speedtest-cli by sivel](https://github.com/sivel/speedtest-cli) aka Python version in the web GUI. Meanwhile, speedtest-official.sh uses 'Speedtest CLI' from Ookla https://www.speedtest.net/apps/cli.

**Comment by brycedjohnson** [comment]
@arevindh I did the update and still getting that syntax error.

@karimnouh That sh script runs the official speedtest directly.  I can run speedtest.sh script which runs the python script and that one works to get the speedtest, although I didn't get the no internet in the database when trying it with a different invalid server, or disconnected my pi from the internet during the test.

**Comment by brycedjohnson** [comment]
@karimnouh Oops yes you were right.  I had the Speedtest official installed at one point and it was working, but must have reverted back to the python script at some point.

Also glossed over the first step somehow just now when reinstalling. Doh.  `Install Speedtest CLI (Important)`

@arevindh Tested it and it works now!  Sorry about the confusion!

**Comment by arevindh** [comment]
Thanks for testing.

**Comment by arevindh** [comment]
@brycedjohnson @karimnouh: Line char or bar chart is better?  ( Changed from bar to line chart along with this change).

**Comment by brycedjohnson** [comment]
Line chart for sure!  I saw that and liked it better.

**Comment by karimnouh** [comment]
Agreed the line chart works way better for a time series.
