### ISSUE TITLE
Not able to disable the speedtest

### ISSUE THREAD

**Issue by nnleaf** [arevindh/pihole-speedtest#44]
Hi, I'm on Pihole 5.0 and I can't set the Speedtest Schedule to disabled. The speedtests are causing spikes in network graphs I'm monitoring on grafana so I wanted to turn them off. I don't want to remove the package as it's useful when diganostics. 

Thanks.

**Comment by arevindh** [comment]
> @P8Kcv6n Seems I missed that one when implementing official speedtest. Fixed now .
> 
> ```
> sudo su
> cd /opt/pihole/
> rm webpage.sh
> wget https://github.com/arevindh/pi-hole/raw/master/advanced/Scripts/webpage.sh
> chmod +x webpage.sh
> ```

@P8Kcv6n can you try same steps now ?

_Originally posted by @arevindh in https://github.com/arevindh/pihole-speedtest/issues/39#issuecomment-641153976_

**Comment by nnleaf** [comment]
Updating it did the trick, thanks!
