### ISSUE TITLE
No Graphs

### ISSUE THREAD

**Issue by Jurgenn22** [arevindh/pihole-speedtest#45]
Hi,
I don't get graphs in the Pihole dashboard page. Instruction manual followed. What am I doing wrong?

**Comment by arevindh** [comment]
Hi @Jurgenn22,
Can you post screenshots and browser console log ?

**Comment by Jurgenn22** [comment]
@arevindh, Thanks for your fast response. What screenshots do you need? From the dashboard? What do you mean by browser console log?

**Comment by arevindh** [comment]
### Console log 
https://support.airtable.com/hc/en-us/articles/232313848-How-to-open-the-developer-console

### Screenshot the front page 
### Check whether this page displays anything 
Login to pihole before opening this url 
 http://pi.hole/admin/api.php?getSpeedData24hrs&PHP

**Comment by Jurgenn22** [comment]
@arevindh Thx.
<img width="1392" alt="Schermafbeelding 2020-06-30 om 13 53 55" src="https://user-images.githubusercontent.com/50082445/86123092-3189b780-bad9-11ea-9c55-618fc23a15b8.png">
<img width="1392" alt="Schermafbeelding 2020-06-30 om 13 54 46" src="https://user-images.githubusercontent.com/50082445/86123147-4cf4c280-bad9-11ea-8264-f061c0c5f15a.png">

**Comment by Jurgenn22** [comment]
@arevindh 
<img width="1280" alt="Schermafbeelding 2020-06-30 om 14 01 47" src="https://user-images.githubusercontent.com/50082445/86123736-49ae0680-bada-11ea-893b-9b244017eb34.png">

**Comment by arevindh** [comment]
Have you configured regular speedtest in settings page ? 
![image](https://user-images.githubusercontent.com/693151/86124720-33637300-baf9-11ea-977d-d89cb6259557.png)

**Comment by Jurgenn22** [comment]
@arevindh 
Yess that's it. How stupid of me. Thank you!

**Comment by arevindh** [comment]
Welcome :)
