### ISSUE TITLE
5.1 Update 

### ISSUE THREAD

**Issue by flipptx** [arevindh/pihole-speedtest#46]
FYI, after update it shows interface is out of date, and dark mode doesn't work.

Pi-hole Version v5.1.1 Web Interface Version v5.0.1 (Update available!) FTL Version v5.1

**Comment by ChrisWNY** [comment]
Seeing the same issue...looks like the pihole-speedtest web UI hasn't updated to 5.1 quite yet.

**Comment by arevindh** [comment]
@ChrisWNY @flipptx working on that .

**Comment by ChrisWNY** [comment]
Newest update worked - had to run the following commands:

_cd /var/www/html/
mv admin org_admin # remove old org_admin folder if exists
git clone https://github.com/arevindh/AdminLTE admin

sudo pihole updatechecker local_

Web UI reports version 5.1 as expected.

  _Pi-hole version is v5.1.1 (Latest: v5.1.1)
  AdminLTE version is v5.1 (Latest: v5.1)
  FTL version is v5.1 (Latest: v5.1)_

**Comment by arevindh** [comment]
> 
> 
> Newest update worked - had to run the following commands:
> 
> _cd /var/www/html/ mv admin org_admin # remove old org_admin folder if exists git clone https://github.com/arevindh/AdminLTE admin sudo pihole updatechecker local_
> 
> Web UI reports version 5.1 as expected.
> 
> _Pi-hole version is v5.1.1 (Latest: v5.1.1) AdminLTE version is v5.1 (Latest: v5.1) FTL version is v5.1 (Latest: v5.1)_
> 
> **** There is a minor bug...in Pi-hole > Settings > API/Web Interface, when setting the Interface Appearance to "Dark", it does flip to Dark and checks the box off for the pi-hole midnight dark theme, but that setting is NOT saved, so going back to the default page switches back to the light theme. I noticed that there is no variable being saved to /etc/pihole/setupVars.conf for the dark theme, which I believe is the problem.
> 
> I worked around it by renaming /var/www/html/admin/style/themes/default-light.css to default-dark.css, simply to force the dark theme to load (otherwise the light theme is the default). It's not a great workaround but until that variable is saved from the Settings page it was the quickest and dirtiest way to get the dark theme to load as the default (I'm also not sure of the variable name used for themes). Not sure if this is a Pi-hole 5.1 bug or a bug within the Speedtest Admin UI.

Seems you missed few steps  Use the manual method https://github.com/arevindh/pihole-speedtest/wiki/Updating--Speedtest-Mod
