### ISSUE TITLE
5.1 Update - unable to change to Dark theme from Settings

### ISSUE THREAD

**Issue by ChrisWNY** [arevindh/pihole-speedtest#47]
After updating to the 5.1 Admin UI for pihole-speedtest, pihole > settings > API/Web Interface > Interface Appearance -- changing to "Dark theme" does set the Dark theme within that page, but the setting/variable for the theme is not saved beyond that. Navigating back to the Dashboard loads the light theme, and going back to the API/Web Interface setting also shows that the UI reverts to the light theme again. 

Though I'm not 100% sure where the theme variable is stored, I'm presuming it should go into /etc/pihole/setupVars.conf. For now, I worked around the issue by saving /var/www/html/admin/style/themes/default-dark.css to default-light.css, after making backups of the originals. Just a quick hack to ensure the dark theme loads regardless of which theme is selected in Settings.

**Comment by arevindh** [comment]
Try   : https://github.com/arevindh/pihole-speedtest/wiki/Updating--Speedtest-Mod

**Comment by ChrisWNY** [comment]
Manual or one-click update? 

curl -sSL https://github.com/arevindh/pihole-speedtest/raw/master/update.sh | bash

**Comment by arevindh** [comment]
try manual

**Comment by ChrisWNY** [comment]
Manual update worked.

Thanks for the quick follow-up. Bought you a few coffees for your work. 


- Chris

**Comment by arevindh** [comment]
@ChrisWNY Thanks a lot.
