### ISSUE TITLE
Issue - Schedule Not Working

### ISSUE THREAD

**Issue by gooch4130** [arevindh/pihole-speedtest#48]
Not sure if this is the right spot, but the scheduler does not seem to work.  I see the entry in crontab but it has not posted a run since configuring yesterday.  I currently have the schedule set to hourly to see if that helps.  Manual runs are fine and show in pihole.  Let me know what data you need.

0 */1 * * * sudo "/var/www/html/admin/scripts/pi-hole/speedtest/speedtest-official.sh"  > /dev/null 2>&1

![image](https://user-images.githubusercontent.com/57266412/88463439-c5546680-ce80-11ea-8e1b-160a3fd87e85.png)

From the below screenshot; these are all manual runs, no 'scheduled' runs are working:
![image](https://user-images.githubusercontent.com/57266412/88463523-5aeff600-ce81-11ea-95f0-b158f48a31fd.png)

**Comment by gooch4130** [comment]
I changed the Speedtest Mode to python, will see if that makes a difference since it triggers a different script.

**Comment by arevindh** [comment]
@gooch4130 : Have you installed https://www.speedtest.net/apps/cli ?

**Comment by gooch4130** [comment]
@arevindh - I had not installed the CLI.  I only followed the install instructions [here](https://github.com/arevindh/pihole-speedtest/wiki/Installing-Speedtest-Mod).  I'll install the CLI - that should do it.  Thank you for getting back to me!

**Comment by gooch4130** [comment]
@arevindh that fixed it; my apologies for not digging more.  Closing this out.

**Comment by P4RI4H** [comment]
Didn't know if I should re-open this topic or start a new one.

I'm having the same issue, except I have speedtest-cli installed, ad it works when I test using the bash script. Just nothing I schedule seems to take. Any ideas?
