### ISSUE TITLE
Graphs not showing properly

### ISSUE THREAD

**Issue by slimyPhlegma** [arevindh/pihole-speedtest#49]
Hi,

I just installed the speedtest you've implemented for pihole. It's working, saving and showing speedtests properly, but if I visit pi.hole/admin at the first place the "Total queries", "Client activity", "Query Types" and "Queries answered by" graphs aren't showing up to the point I hover over them with the mouse. The following picture was taken right after refreshing the pi.hole/admin page:

![speedtestpihole](https://user-images.githubusercontent.com/24920790/88964990-66d91f00-d2aa-11ea-8ab1-2f9daf4c29c4.jpg)

Somehow on the time axis, only one hour is shown at the first place. After hovering over the corresponding graph, it's correctly shown as usually (for the last 24 hours).

**Comment by arevindh** [comment]
Can you check console for any errors ?

**Comment by slimyPhlegma** [comment]
Which logs am I looking for exactly. In the syslog and pihole.log files I can't find any errors.

**Comment by slimyPhlegma** [comment]
I also noticed, that the speedtests aren't run automatically each hour. Instead, I execute them via cron for now.

**Comment by josh3003** [comment]
Yeah I also had this problem with the graphs not showing. I uninstalled the mod and reverted back to default pihole settings.

**Comment by arevindh** [comment]
@josh3003 can you check any errors on browser developer console

**Comment by josh3003** [comment]
@arevindh  you'll have to give me 5 mins to reinstall it again. Hold on

**Comment by arevindh** [comment]
@josh3003 Please clear cache too after installing

**Comment by josh3003** [comment]
@arevindh done the install, ran in icognito mode. Set speedtest schedule and Display range Tick Flush speedtest history (for the first time only) Set speedtest mode to Official CLI.

GO to run the final command: 
`sudo "/var/www/html/admin/scripts/pi-hole/speedtest/speedtest-official.sh" `


get the following result 
```
root@raspberrypi:/opt/pihole# sudo "/var/www/html/admin/scripts/pi-hole/speedtest/speedtest-official.sh"
Testing with
usage: speedtest [-h] [--no-download] [--no-upload] [--bytes] [--share]
                 [--simple] [--csv] [--csv-delimiter CSV_DELIMITER]
                 [--csv-header] [--json] [--list] [--server SERVER]
                 [--exclude EXCLUDE] [--mini MINI] [--source SOURCE]
                 [--timeout TIMEOUT] [--secure] [--no-pre-allocate]
                 [--version]
speedtest: error: unrecognized arguments: --accept-gdpr --accept-license -f json-pretty
2020-08-06 14:05:34     2020-08-06 14:05:35                             0
Error: near ",": syntax error

```

**Comment by arevindh** [comment]
@josh3003 : have you installed this ?
https://www.speedtest.net/apps/cli

**Comment by josh3003** [comment]
@arevindh followed the install instructions and still same result.

**Comment by josh3003** [comment]
@arevindh  tried the one click upgrade
 `sudo "/var/www/html/admin/scripts/pi-hole/speedtest/speedtest-official.sh"`

Still no luck there either.

**Comment by arevindh** [comment]
@josh3003 : `sudo apt-get remove speedtest-cli`

**Comment by josh3003** [comment]
@arevindh That fixed it. Thanks.

**Comment by josh3003** [comment]
@arevindh The graphs also look fine as well. Sounds like my old install was a bit borked. Will monitor and update if there's any issue.

**Comment by arevindh** [comment]
@slimyPhlegma Can you also try the above method ?

**Comment by josh3003** [comment]
@arevindh Hey, bad news. So when you go to the login page I think it displays an empty default speedtest graph? Then when you mouse over the graph it switches back to the query graph. Same happens when you sign in. Same issue as before. Not related to the old python speedtest as I thought. [Check here ](https://imgur.com/a/gCFYwZq)

**Comment by arevindh** [comment]
Can you check browser console for errors

**Comment by josh3003** [comment]
@arevindh what am I looking for? I got no idea what to look out for in the dev console.

**Comment by arevindh** [comment]
@josh3003 : https://javascript.info/devtools

**Comment by josh3003** [comment]
@arevindh https://pastebin.com/8LHAAdBh

**Comment by arevindh** [comment]
Can you check the network tab too ?  Open the tab and reload the page .. Check for any urls with red color.
![image](https://user-images.githubusercontent.com/693151/89513720-8adcb900-d7f2-11ea-85ba-0447b7383a16.png)

**Comment by arevindh** [comment]
If you are have discord, we can troubleshot live 
https://discord.gg/anKMZq
