### ISSUE TITLE
Limit bandwith to e.g. 80%

### ISSUE THREAD

**Issue by Cupcake911** [arevindh/pihole-speedtest#5]
Hello, I love the speedtest integration to pihole. It gives me the ability to have a statistic on my internet speed which is great. My only issue is that when it does the speedtest, it really uses 100% of the bandwith. I've noticed that while playing games like e.g. Rocket League when the game suddendly starts to lag because my raspberry-pi would consume all the bandwith for the speedtest. Would it be possible to sort of limit the bandwith that is used for this?

**Comment by smfoo** [comment]
What's the use of a speed-test if you manipulate the results? And from understanding your scenario is not possible. To limit the speed-test to 80% you have to measure the 100% first => Lag. Or you enter your connection bandwidth manually. But then again there is no reason for a speed-test if you're not really testing the speed;)

**Comment by mschroe82** [comment]
@cupcake you are sure, that you got the sense of such speedtest ?

**Comment by Cupcake911** [comment]
Yeeeee of course I get what you guys mean, but I know that my internet speed can't get any faster then 100 down and 20 up, if only I could limit speedtest.net to only use a maximum of 90 mbit for download and 15 for upload that would be enough for me because the statistics would tell me that the internet connection is stable. I would love to keep it running every hour but in the evenings it get's in the way of my gaming sessions.

**Comment by arevindh** [comment]
@Cupcake911 Guess to you could do that in your firewall or router. 
If you want you can easily write cron according to your needs. Try : [https://crontab-generator.org/](https://crontab-generator.org/)

**Comment by arevindh** [comment]
It can only be implemented once [speedtest-cli git](https://github.com/sivel/speedtest-cli) implements it.
