### ISSUE TITLE
Speedtest Graph Now A Line Graph Rather Than A Bar Graph

### ISSUE THREAD

**Issue by gooch4130** [arevindh/pihole-speedtest#52]
I updated pihole today and Speedtest to the July 29th update, and noticed the speedtest graph (previously a bar graph), is now a line graph.  Is this expected?  Not sure which update would have changed it.

![image](https://user-images.githubusercontent.com/57266412/90079276-7195aa00-dcd5-11ea-9be8-d345893f7c89.png)

pi@pihole:~ $ pihole -v
  Pi-hole version is v5.1.2 (Latest: v5.1.2)
  AdminLTE version is v5.1-5-gbbce2eb8 (Latest: v5.1.1)
  FTL version is v5.2 (Latest: v5.2)

**Comment by karimnouh** [comment]
Yes, its intended, The change was indeed part of the the July 29th update. [#43](https://github.com/arevindh/pihole-speedtest/issues/43#issuecomment-665390354)

**Comment by arevindh** [comment]
@gooch4130 It is intended.

**Comment by arevindh** [comment]
Closing this
