### ISSUE TITLE
Scheduler not working

### ISSUE THREAD

**Issue by P4RI4H** [arevindh/pihole-speedtest#55]
Scheduler will not automatically run speedtest.
Troubleshooting I've done:
 - Uninstalled/reinstalled speedtest
 - Uninstalled/reinstalled official speedtest-cli
 - Ran `sudo "/var/www/html/admin/scripts/pi-hole/speedtest/speedtest-official.sh"` to test
 - Tried switching Speedtest-CLI and Python and tried changing frequency

The test works but I cannot for the life of me get it to run automatically.

**Comment by thexile** [comment]
I concur with @P4RI4H. The scheduler is broken. I have installed pihole-speedtest for a nearly week and no speedtest has been executed automatically yet.

**Comment by arevindh** [comment]
@thexile @P4RI4H can u post output of `sudo crontab -u root -e`

**Comment by thexile** [comment]
![image](https://user-images.githubusercontent.com/7766368/93796592-a4847380-fc6d-11ea-81a8-00a50d6b8cf0.png)

**Comment by smartermoney** [comment]
I will also concur with @P4RI4H and @thexile . I installed speedtest on 2 different pi's and neither will run speedtest. I thought it was something I did till I went searching.

I also ran the suggested (sudo crontab -u root -e) and got the same thing as @thexile (an empty one so I'm not posting the pic)

**Comment by j-broo** [comment]
Concur with above problems. Have tried reinstalling the speedtest mod also. Test script does the following:
```
root@J-Pi:/var/www/html/admin/scripts/pi-hole/speedtest# sudo "/var/www/html/admin/scripts/pi-hole/speedtest/speedtest-official.sh" 
Testing with 
usage: speedtest [-h] [--no-download] [--no-upload] [--bytes] [--share]
                 [--simple] [--csv] [--csv-delimiter CSV_DELIMITER]
                 [--csv-header] [--json] [--list] [--server SERVER]
                 [--exclude EXCLUDE] [--mini MINI] [--source SOURCE]
                 [--timeout TIMEOUT] [--secure] [--no-pre-allocate]
                 [--version]
speedtest: error: unrecognized arguments: --accept-gdpr --accept-license -f json-pretty
2020-09-21 21:44:42	2020-09-21 21:44:51				0				
Error: near ",": syntax error
```

**Comment by arevindh** [comment]
I am working on a fix, please put the following in the file for now.
`0 */1 * * * sudo "/var/www/html/admin/scripts/pi-hole/speedtest/speedtest-official.sh"  > /dev/null 2>&`

**Comment by smartermoney** [comment]
The file has been entered. It does change the time in the file when I change it in the GUI.
I have it set to test hourly. Will update if it does so

**Comment by smartermoney** [comment]
I have it set to run a test every hour. Its been 3 hours and no test has run yet.
When i run sudo "/var/www/html/admin/scripts/pi-hole/speedtest/speedtest-official.sh"
I get an error
![speedtest-error](https://user-images.githubusercontent.com/71663684/93930477-0d5a0300-fce3-11ea-9788-d0314d93af9c.png)

**Comment by smartermoney** [comment]
running hourly as expected now.

**Comment by thexile** [comment]
> 
> 
> I am working on a fix, please put the following in the file for now.
> 
> `0 */1 * * * sudo "/var/www/html/admin/scripts/pi-hole/speedtest/speedtest-official.sh" > /dev/null 2>&`
> 
> After that try changing the schedule from Web UI and check the file again for changes.

Working great now.
![image](https://user-images.githubusercontent.com/7766368/94149987-2dd4b980-feab-11ea-9910-28b295dced9d.png)

**Comment by j-broo** [comment]
I have a weird problem. Wondering if anyone else has experienced this. After applying the above fix, the scheduler works again. My settings are for a speed test every hour, however, every night the 4am speedtest fails, with 0 for ping, download and upload. Anyone else found something similar? Any ideas on where to look for clues?

**Comment by arevindh** [comment]
> 
> 
> I have a weird problem. Wondering if anyone else has experienced this. After applying the above fix, the scheduler works again. My settings are for a speed test every hour, however, every night the 4am speedtest fails, with 0 for ping, download and upload. Anyone else found something similar? Any ideas on where to look for clues?

Most probably it is your internet connection / router issue . If possbile try running ping around 3:55 - 4:05 and logging the result to a file for debugging in the morning.

There was a issue previously with one of the users of this mod , his internet will get disconnected for 2-3 minutes at 2:00 AM everyday . So he wont get any usefull data for that time.

**Comment by j-broo** [comment]
> > I have a weird problem. Wondering if anyone else has experienced this. After applying the above fix, the scheduler works again. My settings are for a speed test every hour, however, every night the 4am speedtest fails, with 0 for ping, download and upload. Anyone else found something similar? Any ideas on where to look for clues?
> 
> @j-broo
> Most probably it is your internet connection / router issue . If possbile try running ping around 3:55 - 4:05 and logging the result to a file for debugging in the morning.
> 
> There was a issue previously with one of the users of this mod , his internet will get disconnected for 2-3 minutes at 2:00 AM everyday . So he wont get any usefull data for that time.

Thanks. Turns out my AP was rebooting daily at 4AM. D'oh!
