### ISSUE TITLE
Suggestion: Readme update.

### ISSUE THREAD

**Issue by Afraidium** [arevindh/pihole-speedtest#56]
When first attempting to use custom servers with this script, I was failing when entering an IP address for the server to test with.
It was not apparent at first that instead of an IP address the server ID is required.

Can you please update the readme with information on using a server ID from [https://c.speedtest.net/speedtest-servers-static.php](https://c.speedtest.net/speedtest-servers-static.php).

I think that would be beneficial for other users who would not read through "speedtest-official.sh".

Thanks for all your work on this.

**Comment by arevindh** [comment]
@Afraidium Thank you, updated wiki.
