### ISSUE TITLE
Feature: average DL, UL and Ping

### ISSUE THREAD

**Issue by j-broo** [arevindh/pihole-speedtest#57]
It would be nice to include and caculate average download, upload and ping stats. These should be the averages over the selected graph period (eg, 7 days) and could be displayed below/above the graph, and recalculated after each speedtest.

For someone like me who is on LTE and has widely varying results (my ISP sucks) this would be nice to get an overall idea of the ISP performance.

**Comment by jolleyutah** [comment]
+1
