### ISSUE TITLE
No Internet

### ISSUE THREAD

**Issue by scotty7d** [arevindh/pihole-speedtest#59]
I have followed the instructions and I am not getting the same results i did in the past. Any suggestions? 
![SpeedTest-NoInternet](https://user-images.githubusercontent.com/65547072/96605343-00cec780-12ee-11eb-9f07-a44c682e681f.JPG)

**Comment by scotty7d** [comment]
Update, it wont let me uninstall (i think) 
![SpeedTest-NoInternet](https://user-images.githubusercontent.com/65547072/96607580-6623b800-12f0-11eb-8fee-280c5c4869f9.JPG)

**Comment by arevindh** [comment]
> 
> 
> Update, it wont let me uninstall (i think)
> ![UninstallSpeedTestMOD](https://user-images.githubusercontent.com/65547072/96607630-7045b680-12f0-11eb-8664-ebfafeb2ff1c.JPG)

try `rm -rf mod_admin` before  `mv admin mod_admin`

**Comment by arevindh** [comment]
Can you post the output of ` speedtest -help`
