### ISSUE TITLE
Time Option

### ISSUE THREAD

**Issue by razereru** [arevindh/pihole-speedtest#60]
Hello, 
would it be possible to perhaps add a "shorted time" like 5 or 15 mins? the sudo "/var/www/html/admin/scripts/pi-hole/speedtest/speedtest-official.sh"  helps to see if it works but it would be great to be able to run the test more often

**Comment by arevindh** [comment]
[Crontab generator](https://crontab-generator.org/) will help you with that . Paste `sudo "/var/www/html/admin/scripts/pi-hole/speedtest/speedtest-official.sh"` in command section . 

Edit and replace the exisitng line using `sudo -u root crontab -e`
