### ISSUE TITLE
Speed test server selection

### ISSUE THREAD

**Issue by razereru** [arevindh/pihole-speedtest#61]
Is the speed test server list something that is kept by the SpeedTest team or by you? it seems to me that the servers that are on the list don't include every country:-( and I would guess that speed test to the same server in the same country would be most "telling-consistent" is there somehow a possibility to add a server?

**Comment by arevindh** [comment]
@razereru The [Speedtest ](https://www.speedtest.net/)os the property of [Ookla ](https://www.speedtest.net/about). This plugin just uses their service.
