### ISSUE TITLE
ETA on update for Pi-hole 5.2? 

### ISSUE THREAD

**Issue by ChrisWNY** [arevindh/pihole-speedtest#65]
New core/web UI/FTL was released today. Looking forward to seeing the latest Pi-hole-Speedtest update for it!

**Comment by ChrisWNY** [comment]
Scratch that...looks like the existing Pi-hole Speedtest works perfectly fine with the new updates.

**Comment by josh3003** [comment]
Think it will need an update for new installs and checkouts. Having the problem now after the upgrade.

**Comment by arevindh** [comment]
@ChrisWNY working on it

**Comment by arevindh** [comment]
@ChrisWNY @josh3003 . Updated, can you check and confirm.

**Comment by ChrisWNY** [comment]
Seems to be working...version info is correctly reported, the new local DNS records menu (including the new CNAME feature) is working as well from initial testing. Will test more thoroughly during the morning EST and will report back if I run into any issues.

Thanks for the quick turnaround!

**Comment by josh3003** [comment]
May need another quick update. Pi-hole Core/Web v5.2.1 and FTL v5.3.2 released.

**Comment by ChrisWNY** [comment]
Yep, Pi-hole was updated yet again today.

**Comment by josh3003** [comment]
Yeah that annoying red flashing update available is annoying lol. I hadn't tested speedtest yet will just wait until 5.2.1 is created and will implement then. Kind of annoying there is probably some check somewhere and you could just hardcode the version number to satisfy that red glow.

**Comment by ChrisWNY** [comment]
I've updated and applied the speedtest Admin repo to the latest Pihole build and everything works fine. You won't trash your Pihole install as all you're doing is overwriting some web pages and a script with the custom speedtest version. If you follow the manual update process it's very simple to revert and only takes a few seconds to do so.

**Comment by arevindh** [comment]
@josh3003 @ChrisWNY : Just some text [changes](https://github.com/pi-hole/AdminLTE/pull/1642/files) . Will update after work hours.

**Comment by arevindh** [comment]
@josh3003 @ChrisWNY  Updated

**Comment by ChrisWNY** [comment]
I grabbed the latest Admin LTE - pihole -v is outputting the following after update:
AdminLTE version is v5.2-6-g7a9e44a9

This causes the web UI to think there is an update still available (and reports the Web UI as 5.2 instead of 5.2.1). Just wanted to double-check. Thanks.

**Comment by arevindh** [comment]
@ChrisWNY  Check now, forgot to create the release.

**Comment by ChrisWNY** [comment]
That worked...version reported properly, everything seems good to go. I'll close this one. Thanks for the quick updates and follow-ups!
