### ISSUE TITLE
Error running speedtest script

### ISSUE THREAD

**Issue by deannreid** [arevindh/pihole-speedtest#66]
when running the test file (sudo "/var/www/html/admin/scripts/pi-hole/speedtest/speedtest-official.sh" )

The following error appears

/opt/pihole# sudo "/var/www/pi.hole/admin/scripts/pi-hole/speedtest/speedtest-official.sh"
Testing with
usage: speedtest [-h] [--no-download] [--no-upload] [--single] [--bytes]
                 [--share] [--simple] [--csv] [--csv-delimiter CSV_DELIMITER]
                 [--csv-header] [--json] [--list] [--server SERVER]
                 [--exclude EXCLUDE] [--mini MINI] [--source SOURCE]
                 [--timeout TIMEOUT] [--secure] [--no-pre-allocate]
                 [--version]
speedtest: error: unrecognized arguments: --accept-gdpr --accept-license -f json-pretty
2020-12-22 20:41:25     2020-12-22 20:41:26                             0
Error: near ",": syntax error

**Comment by arevindh** [comment]
Please change to official CLI
