### ISSUE TITLE
New Pi-hole release 5.2.2

### ISSUE THREAD

**Issue by ChrisWNY** [arevindh/pihole-speedtest#67]
New Pi-hole released today, 12/24. Looks like speedtest will likely need another minor update for the new version.

**Comment by arevindh** [comment]
Working on it.

**Comment by arevindh** [comment]
@ChrisWNY updated, can you check and confirm?

**Comment by ChrisWNY** [comment]
Updated to latest speedtest admin repo...looks good, no issues. Thanks for the quick update! Enjoy your holiday!

**Comment by ChrisWNY** [comment]
Problem seems to have sorted itself out overnight...list of speedtest servers seems to have changed. 

Thanks for the quick turnaround and enjoy your holiday and New Year! I'll close this one out.
