### ISSUE TITLE
Another Pi-hole update - 5.2.3/5.3/5.4

### ISSUE THREAD

**Issue by ChrisWNY** [arevindh/pihole-speedtest#68]
Pi-hole was just updated. Change log for the web UI:
https://github.com/pi-hole/AdminLTE/releases/v5.3

Just a heads-up and look forward to another speedtest update!

**Comment by arevindh** [comment]
Hey, @ChrisWNY was out for a few days. Started the update now.

**Comment by ChrisWNY** [comment]
Sounds good...can test that out for you in the AM tomorrow (EST) once it's ready. Thanks!

**Comment by arevindh** [comment]
@ChrisWNY Updated

**Comment by ChrisWNY** [comment]
Everything looks good...installed earlier this AM (EST), no issues, correct version reported. Thanks yet again for the quick turnaround. Will close this one!
