### ISSUE TITLE
Another pi-hole update - 1/19/2021

### ISSUE THREAD

**Issue by ChrisWNY** [arevindh/pihole-speedtest#69]
Looks like the web UI only saw a couple minor changes in the latest update...

https://github.com/pi-hole/AdminLTE/releases/v5.3.1

Core is 5.3.4 and FTL is 5.5.1.

**Comment by arevindh** [comment]
Working on it

**Comment by arevindh** [comment]
@ChrisWNY Updated

**Comment by ChrisWNY** [comment]
Good to go! Thanks!
