### ISSUE TITLE
Speedtest - list of servers

### ISSUE THREAD

**Issue by ChrisWNY** [arevindh/pihole-speedtest#70]
What determines which servers are listed within the following link below?

https://c.speedtest.net/speedtest-servers-static.php

I've noticed that generally-speaking, speedtest servers that are physically nearby are listed on that XML page. Lately, however, it's been all over the place (I'm located in the NE US, and that list is showing speedtest servers in the NW US). 

Within the Pi-hole Speedtest settings page, I generally use a custom Server ID based on location, and I get consistent speedtest results from that particular server (at least for a couple of weeks or so). Lately that functionality hasn't been reliable because the speedtest list is always changing, causing a server ID that I've entered manually from the Speedtest list of servers to disappear. 

Is there any way around this issue? I'm using the Official Speedtest CLI btw.

**Comment by ChrisWNY** [comment]
I guess this could turn into an enhancement request...perhaps allowing input of the speedtest server URL within settings instead of ID. That XML file appears to be unreliable and changes randomly based on circumstances that are unknown.

**Comment by arevindh** [comment]
@ChrisWNY unfortunately there is no option available to use URLs. All I can do is list the nearby servers, may be will add that in a future release.

**Comment by ChrisWNY** [comment]
Understood - the issue seems to be related to what gets populated into the nearby servers XML file. Seems to vary wildly sometimes. Haven't figured it out.
