### ISSUE TITLE
Pi-hole web UI v5.3.2/FTL v5.6

### ISSUE THREAD

**Issue by ChrisWNY** [arevindh/pihole-speedtest#71]
Pi-hole released updates for the web UI and FTL. Web UI changes appear to be minor again:

https://github.com/pi-hole/AdminLTE/releases/v5.3.2

**Comment by arevindh** [comment]
Already updated.
https://github.com/arevindh/AdminLTE/pull/33

**Comment by ChrisWNY** [comment]
Looks good! Closing this one.
