### ISSUE TITLE
Angles of time on dashboard graph not present

### ISSUE THREAD

**Issue by town3r** [arevindh/pihole-speedtest#72]
The time labels of the dashboard graph are not angled like the others resulting in text being covered.

![image](https://user-images.githubusercontent.com/12396203/107229907-00b11f80-69e4-11eb-8c05-ee15ad3d6530.jpeg)

**Comment by arevindh** [comment]
@zelrone Can you take a look at it.

**Comment by town3r** [comment]
Is there a specific file that has the configuration of how things are displayed on the graph that I could test a few things?

**Comment by arevindh** [comment]
@town3r I tried a few things but the current one is the best I could do.

**Comment by town3r** [comment]
Guessing no, but is it possible to just copy the graph style of Total Queries & Client activity?

I'm digging into the AdminLTE-master files a bit to see if i can find where you added the Speedtest graph.
Was the code to add the speedtest graph just merged with the existing datatables css file or is there a separate new one?

Apologies for all the questions. first time really looking at the files and seeing where things are

**Comment by arevindh** [comment]
@town3r  Js file is available here `https://github.com/arevindh/AdminLTE/blob/master/scripts/pi-hole/js/speedtest.js`. 

If you are successful a pull request is appreciated.

**Comment by town3r** [comment]
Thank you!
Super new to JS and really Github was well so no idea how to perform a pull request.
Did find removing `Do` from the `(itemdate).format("Do HH:mm")` line seems to help when viewing on mobile.
and modifying the `maxTicksLimit` from `10` to `20` helped as well.

![IMG_1024](https://user-images.githubusercontent.com/12396203/115051136-1dfde080-9ea2-11eb-9cfa-450115552a55.jpg)

Haven't been able to figure out how to change the color of the text or have them rotate to fit correctly yet.

**Comment by arevindh** [comment]
@town3r now it's missing date right?

**Comment by town3r** [comment]
Yeah, which I'm ok with. 

I was more wanting it to mirror what the other graphs look like & display on the admin dashboard.

When it's only showing the last 24 some hours the date isn't really needed.

**Comment by arevindh** [comment]
> When it's only showing the last 24 some hours the date isn't really needed.

But it is not good for more than a day.

**Comment by town3r** [comment]
Hit up the discourse.pi-hole.net forum to see if maybe someone knows how the Pihole devs configured their fancy dashboard graphs.

https://discourse.pi-hole.net/t/pihole-dashboard-graph-configuration-file-location/46817

**Comment by town3r** [comment]
Can this be reopened?
