### ISSUE TITLE
Help: PiHole Webpage isn't responding /  Terminal: Error: no such table: speedtest

### ISSUE THREAD

**Issue by Goayandi** [arevindh/pihole-speedtest#73]
Hey guys,

I tried to install Speedtest for my Pihole following your instructions. However, the web panel in PiHole does not work - as you can see on the screenshot. It gets stuck in the processing mode.  When using the terminal / ssh command it shows:

Testing with 
2021-02-13 13:27:30     2021-02-13 13:27:47     Vodafone Germany DSL    178.x.xxx.xxx    UIT Services GmbH       0       8.74    49.1601 9.60203 https://www.speedtest.net/result/c/anonymized
Error: no such table: speedtest

Do you have any advice for me?

![Screenshot (278)](https://user-images.githubusercontent.com/16936763/107850100-300ac680-6e00-11eb-982e-1813000824a5.png)

**Comment by arevindh** [comment]
Can you try to uninstall and reinstall 

Uninstall : https://github.com/arevindh/pihole-speedtest/wiki/Uninstalling-Speedtest-Mod

Installing : https://github.com/arevindh/pihole-speedtest/wiki/Installing-Speedtest-Mod

**Comment by arevindh** [comment]
Closing the issues, please reopen if issues persist.
