### ISSUE TITLE
Pi-hole FTL v5.7 and Web v5.4 released

### ISSUE THREAD

**Issue by town3r** [arevindh/pihole-speedtest#74]
Pi-hole released updates for the web UI and FTL.:

https://github.com/pi-hole/AdminLTE/releases/tag/v5.4

https://pi-hole.net/2021/02/16/pi-hole-ftl-v5-7-and-web-v5-4-released/

**Comment by town3r** [comment]
I'm guessing having the mod installed is what's preventing me from updating to WebUI v5.4

**Comment by ChrisWNY** [comment]
You can update to Web UI v5.4 by following the instructions to "Revert Admin" and "Revert Pi-hole", this will replace the speedtest mod web UI with the latest Pi-hole web UI. Running "pihole -up" after reverting will update you to the latest Pi-hole.

https://github.com/arevindh/pihole-speedtest/wiki/Updating--Speedtest-Mod

Until pihole-speedtest is updated, getting the latest speedtest admin repo will set you back to Web UI v5.3.2. You can still use the speedtest admin repo with the latest Pihole Core and FTL, having a slightly older admin UI won't cause problems. Should still work just fine. I'm sure the speedtest admin repo will be updated soon though.

**Comment by arevindh** [comment]
@ChrisWNY Thank you for explaining, I was a bit busy with office works. 

Just updated the mod to v5.4.

**Comment by arevindh** [comment]
@ChrisWNY Let me know if you face any issues.

**Comment by ChrisWNY** [comment]
Grabbed the latest repo just now, everything seems in working order. Thanks for another quick update!
