### ISSUE TITLE
Feature : Detailed Speedtest History

### ISSUE THREAD

**Issue by arevindh** [arevindh/pihole-speedtest#76]
Planing to add a detailed history page of what pihole provides.

![image](https://user-images.githubusercontent.com/693151/111619431-94f47a80-880b-11eb-82ed-d2e0fdda0abd.png)

@ChrisWNY Any more suggestions to add?

**Comment by ChrisWNY** [comment]
Looks good - a detailed speedtest history graph would definitely be a useful feature.

More control over the specific speedtest server to use would be useful...the XML custom speedtest file seems to change randomly based on location data (sometimes I'll specify a certain speedtest server and it'll disappear from that XML file randomly, causing errors, 0mbps up/down ends up plotted on the graph). Not sure how that would be logically feasible to accomplish however depending on how that has been coded.

**Comment by arevindh** [comment]
@ChrisWNY I was working on a standalone version, how does it look ?

![image](https://user-images.githubusercontent.com/693151/112798953-507aa180-908b-11eb-8722-b0a2884b5453.png)

**Comment by arevindh** [comment]
@ChrisWNY Would you like to test a new standalone version (Docker) for the speedtest mod?

**Comment by ChrisWNY** [comment]
Yes absolutely - let me know how to go about installing (will it be ok running on the same device as Pi-hole?) and I will test it from my end. Look forward to it!

**Comment by arevindh** [comment]
> Yes absolutely - let me know how to go about installing (will it be ok running on the same device as Pi-hole?) and I will test it from my end. Look forward to it!

Which device are you using to run pihole ?

**Comment by arevindh** [comment]
Try this docker 

https://hub.docker.com/repository/docker/arevindh/homelab-tracker

**Comment by arevindh** [comment]
Its updated now : https://hub.docker.com/r/arevindh/homelab-tracker

**Comment by arevindh** [comment]
@ChrisWNY Did you try it ?

**Comment by ChrisWNY** [comment]
I will finish testing in a few hours and provide feedback in this thread. Apologies for the delay - I was out of town for business the past couple of weeks but am home now. Will have this done shortly.

**Comment by arevindh** [comment]
Closing this since since the feature is moved to  https://hub.docker.com/r/arevindh/homelab-tracker
