### ISSUE TITLE
403  Forbidden | https://ookla.bintray.com/debian

### ISSUE THREAD

**Issue by town3r** [arevindh/pihole-speedtest#77]
Is anyone else getting this error message from the official speedtest repo when attempting to run `sudo apt update` ?

`Err:2 https://ookla.bintray.com/debian buster InRelease
  403  Forbidden [IP: 34.214.237.80 443]
Hit:3 http://raspbian.raspberrypi.org/raspbian buster InRelease
Reading package lists... Done              
E: Failed to fetch https://ookla.bintray.com/debian/dists/buster/InRelease  403  Forbidden [IP: 34.214.237.80 443]
E: The repository 'https://ookla.bintray.com/debian buster InRelease' is no longer signed.`

**Comment by town3r** [comment]
Looks like the JFrog hosting site is shutting down it's bintray service soon and today they had pre-planned brown-outs which is likely the cause of the 403 errors.

[https://bintray.com/ookla/debian/speedtest-cli](https://bintray.com/ookla/debian/speedtest-cli)

> April 12th, 26th, 2021	We will have some short service brown-outs to remind users about the services that are going away on May 1st. (Specific hours will be advertised in the Bintray status page.)

> Attention: All Bintray services will be deprecated and your accounts will be disabled on May 1st 2021. [Learn More](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter).

**Comment by town3r** [comment]
[BinTray Status](https://status.bintray.com/)

Schedule brown-out session on April 12th 6AM to 2PM Pacific Daylight Time

**In progress** - Scheduled maintenance is currently in progress. We will provide updates as necessary.

Apr 12, 13:00 UTC
**Scheduled** - Scheduled brown-out session to warn users about May 1st as sunset date for Bintray.

Artifactory installations with remote repositories configured against JCenter, GoCenter and ChartCenter will not be affected by this sunset.

We recommend that JFrog Cloud customers continue using jcenter.bintray.com, gocenter.io, and repo.chartcenter.io as Artifactory remote repositories going forward.

JFrog self-hosted customers can also continue fetching from these repositories, but are encouraged to migrate to the canonical repositories.

Additional details can be found at https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by town3r** [comment]
I've sent an email to support@ookla.com asking what they're plans are once JFrog EOLs their current BinTray hosting service.

**Comment by town3r** [comment]
Update from Ookla Support:
> Yes, we are having issues with our CLI at the moment.
Our engineering is aware of it and working to fix it as we speak.

**Comment by town3r** [comment]
Issue doesn't seem to be occurring anymore. 🥳

**Comment by arevindh** [comment]
Great :partying_face: .

> Issue doesn't seem to be occurring anymore.
