### ISSUE TITLE
Dashboard not updating after installing speedtest

### ISSUE THREAD

**Issue by rodhammond** [arevindh/pihole-speedtest#78]
Even after reboot, dashboard charts do not populate or automatically update after installing speedtest. If I mouse over each chart, they "fill" in.   If speedtest is uninstalled, dashboard works correctly.

x86
Pi-hole v5.2.4
Web Interface v5.4
FTL v5.7

**Comment by arevindh** [comment]
Please check after few hours, new update is pending

**Comment by arevindh** [comment]
@rodhammond can you post some video/gif?

**Comment by rodhammond** [comment]
Thanks for the update. Everything is working correctly  :)
