### ISSUE TITLE
cant switch to CLI mode

### ISSUE THREAD

**Issue by flipptx** [arevindh/pihole-speedtest#80]
been running the python version for all this time, updated yesterday saw the test hasn't ran since, so figured i should update to the CLI version but i cant seem to get it to work. do you have a nice BASH script to remove the python version and swap over to the new CLI version?

**Comment by arevindh** [comment]
No scripts currently . 

Try any of the below 

`sudo pip3 uninstall speedtest-cli`

OR

`sudo pip uninstall speedtest-cli`

OR

`sudo apt-get remove speedtest-cli`

Installs https://www.speedtest.net/apps/cli

**Comment by flipptx** [comment]
which option for raspbian

**Comment by arevindh** [comment]
Try everything ..

**Comment by flipptx** [comment]
it seems to install but when i type speediest in terminal "-bash: /usr/local/bin/speedtest: No such file or directory"

**Comment by flipptx** [comment]
got it, looks like its a bug with ssh sessions!

**Comment by arevindh** [comment]
Did this one ? Install https://www.speedtest.net/apps/cli 

Ps. use the debian/ ubuntu option

**Comment by flipptx** [comment]
yep the debian one works in terminal have i had to clear my SSH Sessions, but the results from term don't seem show in pihole, ill have to wait a few hours for it to auto run then i guess? (not sure if its possible but it would be great if there was a "test now option" in the GUI

**Comment by arevindh** [comment]
Did you set the Test interval ? 

Test now using . `sudo /var/www/html/admin/scripts/pi-hole/speedtest/speedtest-official.sh` 

I am making a standalone [version](https://hub.docker.com/r/arevindh/homelab-tracker) with more features .

**Comment by flipptx** [comment]
its working now, thanks
