### ISSUE TITLE
How to run a test every quarter of an hour

### ISSUE THREAD

**Issue by pce5962** [arevindh/pihole-speedtest#84]
Good evening,
I followed your installation to set up the speedtest on my pi hole which is hosted on a rapsberry.
I have a question, I would like to be able to perform a test every 15 minutes of the hour, at 0, 15, 30 and 45, what should be changed?

**Comment by arevindh** [comment]
@ChrisWNY should remove the drop-down picker and add a text field that accepts crontab?

**Comment by ChrisWNY** [comment]
@arevindh the drop-down is definitely the more user-friendly option, maybe and "advanced" collapsible UI element that would allow someone to input a schedule in proper crontab format?
