### ISSUE TITLE
Pi-hole speed test not working

### ISSUE THREAD

**Issue by brian6g** [arevindh/pihole-speedtest#85]
Installed to pi 4, run latest updates, get the following errors

when run “ Test Pihole speedtest from commandline“ get following error
Testing with 
/var/www/html/admin/scripts/pi-hole/speedtest/speedtest-official.sh: line 20: /usr/bin/speedtest: No such file or directory.

Web graphic shows speed test ever hour, but results zero.
If I run “ pihole -a -sn” at command line then it does speed test and updates web graphic.

not sure what the problem is, installed Speedtest a couple of times, same problem?

**Comment by arevindh** [comment]
Can you post the output of `whereis speedtest`

**Comment by brian6g** [comment]
This is the output from “where is Speedtest

speedtest: /usr/local/bin/speedtest

**Comment by arevindh** [comment]
@brian6g will update with new instructions this weekend .
