### ISSUE TITLE
Webserver graphs are not displaying correctly

### ISSUE THREAD

**Issue by yanniedog** [arevindh/pihole-speedtest#86]
First: I really love your mod. Fantastic. I'll buy you a coffee after this post.

After installing this mod, the Speedtest graph always loads correctly, but it has caused a problem with how the original graphs on the pihole dashboard load

These graphs only show up if I **move my mouse cursor** over these them, or the **graphs automatically refresh**.
They don't display automatically when the page loads (even after hitting 'refresh')

Please see the attached screenshots

![image](https://user-images.githubusercontent.com/25560742/121624087-35c59f80-cab4-11eb-8861-820d3f06fb80.png)
![image](https://user-images.githubusercontent.com/25560742/121624105-40803480-cab4-11eb-988b-8ad66caa5188.png)

**Comment by arevindh** [comment]
Which browser and version are you using ? Any console errors ?

**Comment by yanniedog** [comment]
Google Chrome Version 91.0.4472.101 (Official Build) (64-bit).
I have rechecked the webserver using the Pi's own browser (Chromium), and the same thing happens

The Pi appears to be working normally. 
What do you mean by console errors? 
Is there a log file I can send you?

**Comment by AftDawn** [comment]
Hi there, my speedtest graph is not even showing up
![image](https://user-images.githubusercontent.com/42480566/125053906-f60cca80-e0e8-11eb-9b77-50a96306da30.png)

i'm also getting CSP errors inside of Brave
![image](https://user-images.githubusercontent.com/42480566/125054020-19377a00-e0e9-11eb-954b-143c6bbd044c.png)
![image](https://user-images.githubusercontent.com/42480566/125054061-26546900-e0e9-11eb-8663-7ddf6a081f17.png)

**Comment by AftDawn** [comment]
I tried removing img-src from the CSP but that made every image not load (i don't know anything about php or the CSP part of html) so i added it back again.

**Comment by arevindh** [comment]
@AftDawn seems like your test does not yet run. Can you help me with the result of `<pihole-ip>/"api.php?getSpeedData24hrs&PHP`  (Please remove / hide IP address before posting here )

**Comment by AftDawn** [comment]
nevermind, it just seems that i needed to wait a day. tho i'm still having to mouse over the charts to get the info
![image](https://user-images.githubusercontent.com/42480566/125154912-e00e1100-e19f-11eb-9ecc-3efc48fddc8b.png)

**Comment by amorshc** [comment]
Adding to this.  I would like to see labels on the sides for Ping vs Speed.  As you can clearly see my graph looks a bit weird because normally it's pretty steady, but when a huge spike in ping occurs, it throws the graph all funky.

![image](https://user-images.githubusercontent.com/23526787/150825483-a31be0e6-0331-4842-87ce-dd427e0090f2.png)

**Comment by arevindh** [comment]
@amorshc added a new update to enable labels .

**Comment by amorshc** [comment]
> @amorshc added a new update to enable labels .

Looks great!  I love the functionality of this, and appreciate you adding the labels!
