### ISSUE TITLE
Unable to set Speedtest schedule from Dashboard

### ISSUE THREAD

**Issue by yanniedog** [arevindh/pihole-speedtest#87]
I wonder if it is because there (? appears) to be a spelling error in your script. I'm not sure if it is causing an issue

In: https://raw.githubusercontent.com/arevindh/pi-hole/master/advanced/Scripts/webpage.sh
"ChageSpeedTestSchedule" (**Chage**, rather than _Change_)

** The only way I was able to get your software to execute on a set schedule was:
`exit` 
(ie, exit OUT of the superuser)
`crontab -e`
Then added the following to the last line
`*/30 * * * * sudo "/var/www/html/admin/scripts/pi-hole/speedtest/speedtest-official.sh"`
(in this case, I wanted the speedtest to occur on every half hour, but anyone reading this can customise the schedule to fit their needs by going to this site: [cronguru](https://crontab.guru/examples.html))

It appears that your superuser cronjob doesn't function correctly for the standard 'pi' user

**Comment by arevindh** [comment]
`ChageSpeedTestSchedule` does not cause the issue since its written the same on both sides .  Can you answer few questions 

1. Which is your OS and Version  ?
2. Which device are you running it on ?
3. Is it a fresh install ?

**Comment by yanniedog** [comment]
RPi3B+
Operating System: Raspbian GNU/Linux 10 (buster)
Kernel: Linux 5.10.17-v7+
All fully updated
Fresh installation
