### ISSUE TITLE
Please automate the installation of Speedtest

### ISSUE THREAD

**Issue by yanniedog** [arevindh/pihole-speedtest#88]
Users (such as myself) 

- went here (https://www.speedtest.net/apps/cli)
- clicked the "Ubuntu/Debian" section
- followed the instructions
`curl -s https://install.speedtest.net/app/cli/install.deb.sh | sudo bash`
- got this response:
`This distribution version is not currently supported via package management, please use the direct download builds per architecture found at https://www.speedtest.net/apps/cli`
- went back here (https://www.speedtest.net/apps/cli)
- went to the bottom of the page (Download Speedtest CLI)
- Clicked "Linux"
- Clicked "arm" (here [this link]](https://install.speedtest.net/app/cli/ookla-speedtest-1.0.0-arm-linux.tgz)
- Opened the package in raspian's xarchiver
- extracted the 3 files to the /tmp directory
![image](https://user-images.githubusercontent.com/25560742/121625638-30b61f80-cab7-11eb-975d-1427f448ce3b.png)
- then went back to [your page](https://github.com/arevindh/pihole-speedtest/wiki/Installing-Speedtest-Mod) and completed the remaining instructions
- started scratching our heads when this command didn't work "sudo "/var/www/html/admin/scripts/pi-hole/speedtest/speedtest-official.sh" 
Before finally understanding that the 3 speedtest files we extracted to the /tmp folder need to be moved to the /usr/bin folder (as sudo)

This part is very cumbersome and required users to troubleshoot their way through the installation. Your instructions didn't indicate that we needed to move the speedtest, speedtest.md and speedtest.5 files into the /usr/bin folder

Is it possible for these steps to be incorportated into your scripts (or at least include the commands to move the extracted speedtest files in your installation instructions)?

**Comment by arevindh** [comment]
@yanniedog Guess they changed the installation method. It was straight forward when the instructions were written, just install deb package and everything was done . Let me see what I can do this weekend .

**Comment by yanniedog** [comment]
Much appreciated

**Comment by arevindh** [comment]
Updated the [doc ](https://github.com/arevindh/pihole-speedtest/wiki/Installing-Speedtest-Mod)for now.

**Comment by yanniedog** [comment]
> Updated the [doc ](https://github.com/arevindh/pihole-speedtest/wiki/Installing-Speedtest-Mod)for now.

Thank you, will try it out shortly

**Comment by town3r** [comment]
Which version would a Raspberry Pi 4 Model B need?

i386
x86_64
arm
armhf
aarch64

**Comment by arevindh** [comment]
@town3r 

Raspberry Pi can only have `armhf` / `aarch64` . You can choose `armhf` if you are running Raspbian / Raspberry Pi OS. 

`uname -a` will show your exact version .

**Comment by hasan0610** [comment]
canu make like a curl command that will do all the installing for u including the speedtest cli jq sqlite and like everything

**Comment by jgwehr** [comment]
Thanks arevindh! One suggestion for your wiki:

> Update https://github.com/arevindh/pihole-speedtest/wiki/Updating--Speedtest-Mod#install-speedtest-cli----important-
> to point to your new https://github.com/arevindh/pihole-speedtest/wiki/Installing-Speedtest-Mod#install-speedtest-cli
> 

At the moment it sends people to the faulty https://www.speedtest.net install instructions

**Comment by jgwehr** [comment]
Following these instructions from the speedtest repo worked well for me:

> git clone https://github.com/sivel/speedtest-cli.git
> cd speedtest-cli
> python setup.py install

**Comment by arevindh** [comment]
@jgwehr python version is unreliable

**Comment by arevindh** [comment]
@jgwehr The update instructions were not updated  Just updated now.
