### ISSUE TITLE
Pi-hole core, FTL, and web updated - 12/22/21

### ISSUE THREAD

**Issue by ChrisWNY** [arevindh/pihole-speedtest#96]
Pi-hole version 5.7/FTL version 5.12/Web Interface version 5.9

https://github.com/pi-hole/pi-hole/releases/tag/v5.7

https://github.com/pi-hole/FTL/releases/v5.12

Numerous changes have been made to the Pi-hole web interface (v5.9):

https://github.com/pi-hole/AdminLTE/releases/v5.9

Just a heads-up as I'm sure the speedtest admin repo will need another update for this one. Thanks!

**Comment by gasb91** [comment]
What happens if I update ?

**Comment by ChrisWNY** [comment]
Follow the update instructions on the Github page...perfectly fine to update to the latest Core and FTL. The web portion will update as well and you won't see the speedtest graph but all of your data will remain intact. You can go ahead and grab the speedtest admin repo, Pi-hole will simply show that your web core is not up-to-date but Sid usually releases an update within a few days of a Pi-hole release. It's perfectly fine to run the older web core (speedtest admin repo) over the most current Pi-hole core and FTL, everything will still work as it did before.

**Comment by arevindh** [comment]
@ChrisWNY working on the update.

**Comment by arevindh** [comment]
@ChrisWNY @gasb91 Updated to the latest version, please mention if any problems occur.

**Comment by ChrisWNY** [comment]
Looks good! New version info properly displayed, the new Pi-hole web UI templates, etc. all seem to work. No issues. Thanks!
