### ISSUE TITLE
Unable set timezone

### ISSUE THREAD

**Issue by corasaniti** [arevindh/pihole-speedtest#99]
I'd like to set the time zone to Europe/Rome. I entered it as a parameter in the docker-compose

TZ: 'Europe/Rome'

but the graph is always one hour behind the time in Rome.
How can I do? 
Thank you

**Comment by arevindh** [comment]
Is your Timezone observing DST ?

**Comment by corasaniti** [comment]
no my time zone observes solar time The time in Rome is 18.15

**Comment by arevindh** [comment]
> no my time zone observes solar time The time in Rome is 18.15

What about the pihole graph, is it correct ?

**Comment by corasaniti** [comment]
Hi when you upgrade to
Pi-hole v5.8.1 FTL v5.13 Web Interface v5.10.1
Thank you
